# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from typing import Any, Optional, TYPE_CHECKING

from azure.mgmt.core import AsyncARMPipelineClient
from msrest import Deserializer, Serializer

if TYPE_CHECKING:
    # pylint: disable=unused-import,ungrouped-imports
    from azure.core.credentials_async import AsyncTokenCredential

from ._configuration import NotesConfiguration
from .operations import GroupsOperations
from .operations import GroupsOnenoteOperations
from .operations import GroupsOnenoteNotebooksOperations
from .operations import GroupsOnenoteNotebooksSectionGroupsOperations
from .operations import GroupsOnenoteNotebooksSectionGroupsSectionsOperations
from .operations import GroupsOnenoteNotebooksSectionGroupsSectionsPagesOperations
from .operations import GroupsOnenoteNotebooksSectionsOperations
from .operations import GroupsOnenoteNotebooksSectionsPagesOperations
from .operations import GroupsOnenoteNotebooksSectionsParentSectionGroupOperations
from .operations import GroupsOnenotePagesOperations
from .operations import GroupsOnenotePagesParentNotebookOperations
from .operations import GroupsOnenotePagesParentNotebookSectionGroupsOperations
from .operations import GroupsOnenotePagesParentNotebookSectionGroupsSectionsOperations
from .operations import GroupsOnenotePagesParentNotebookSectionsOperations
from .operations import GroupsOnenotePagesParentNotebookSectionsParentSectionGroupOperations
from .operations import GroupsOnenotePagesParentSectionOperations
from .operations import GroupsOnenotePagesParentSectionParentNotebookOperations
from .operations import GroupsOnenotePagesParentSectionParentNotebookSectionGroupsOperations
from .operations import GroupsOnenotePagesParentSectionParentSectionGroupOperations
from .operations import GroupsOnenotePagesParentSectionParentSectionGroupParentNotebookOperations
from .operations import GroupsOnenoteSectionGroupsOperations
from .operations import GroupsOnenoteSectionGroupsParentNotebookOperations
from .operations import GroupsOnenoteSectionGroupsParentNotebookSectionsOperations
from .operations import GroupsOnenoteSectionGroupsParentNotebookSectionsPagesOperations
from .operations import GroupsOnenoteSectionGroupsSectionsOperations
from .operations import GroupsOnenoteSectionGroupsSectionsPagesOperations
from .operations import GroupsOnenoteSectionGroupsSectionsPagesParentNotebookOperations
from .operations import GroupsOnenoteSectionGroupsSectionsParentNotebookOperations
from .operations import GroupsOnenoteSectionsOperations
from .operations import GroupsOnenoteSectionsPagesOperations
from .operations import GroupsOnenoteSectionsPagesParentNotebookOperations
from .operations import GroupsOnenoteSectionsPagesParentNotebookSectionGroupsOperations
from .operations import GroupsOnenoteSectionsParentNotebookOperations
from .operations import GroupsOnenoteSectionsParentNotebookSectionGroupsOperations
from .operations import GroupsOnenoteSectionsParentSectionGroupOperations
from .operations import GroupsOnenoteSectionsParentSectionGroupParentNotebookOperations
from .operations import SitesOperations
from .operations import SitesOnenoteOperations
from .operations import SitesOnenoteNotebooksOperations
from .operations import SitesOnenoteNotebooksSectionGroupsOperations
from .operations import SitesOnenoteNotebooksSectionGroupsSectionsOperations
from .operations import SitesOnenoteNotebooksSectionGroupsSectionsPagesOperations
from .operations import SitesOnenoteNotebooksSectionsOperations
from .operations import SitesOnenoteNotebooksSectionsPagesOperations
from .operations import SitesOnenoteNotebooksSectionsParentSectionGroupOperations
from .operations import SitesOnenotePagesOperations
from .operations import SitesOnenotePagesParentNotebookOperations
from .operations import SitesOnenotePagesParentNotebookSectionGroupsOperations
from .operations import SitesOnenotePagesParentNotebookSectionGroupsSectionsOperations
from .operations import SitesOnenotePagesParentNotebookSectionsOperations
from .operations import SitesOnenotePagesParentNotebookSectionsParentSectionGroupOperations
from .operations import SitesOnenotePagesParentSectionOperations
from .operations import SitesOnenotePagesParentSectionParentNotebookOperations
from .operations import SitesOnenotePagesParentSectionParentNotebookSectionGroupsOperations
from .operations import SitesOnenotePagesParentSectionParentSectionGroupOperations
from .operations import SitesOnenotePagesParentSectionParentSectionGroupParentNotebookOperations
from .operations import SitesOnenoteSectionGroupsOperations
from .operations import SitesOnenoteSectionGroupsParentNotebookOperations
from .operations import SitesOnenoteSectionGroupsParentNotebookSectionsOperations
from .operations import SitesOnenoteSectionGroupsParentNotebookSectionsPagesOperations
from .operations import SitesOnenoteSectionGroupsSectionsOperations
from .operations import SitesOnenoteSectionGroupsSectionsPagesOperations
from .operations import SitesOnenoteSectionGroupsSectionsPagesParentNotebookOperations
from .operations import SitesOnenoteSectionGroupsSectionsParentNotebookOperations
from .operations import SitesOnenoteSectionsOperations
from .operations import SitesOnenoteSectionsPagesOperations
from .operations import SitesOnenoteSectionsPagesParentNotebookOperations
from .operations import SitesOnenoteSectionsPagesParentNotebookSectionGroupsOperations
from .operations import SitesOnenoteSectionsParentNotebookOperations
from .operations import SitesOnenoteSectionsParentNotebookSectionGroupsOperations
from .operations import SitesOnenoteSectionsParentSectionGroupOperations
from .operations import SitesOnenoteSectionsParentSectionGroupParentNotebookOperations
from .operations import UsersOperations
from .operations import UsersOnenoteOperations
from .operations import UsersOnenoteNotebooksOperations
from .operations import UsersOnenoteNotebooksSectionGroupsOperations
from .operations import UsersOnenoteNotebooksSectionGroupsSectionsOperations
from .operations import UsersOnenoteNotebooksSectionGroupsSectionsPagesOperations
from .operations import UsersOnenoteNotebooksSectionsOperations
from .operations import UsersOnenoteNotebooksSectionsPagesOperations
from .operations import UsersOnenoteNotebooksSectionsParentSectionGroupOperations
from .operations import UsersOnenotePagesOperations
from .operations import UsersOnenotePagesParentNotebookOperations
from .operations import UsersOnenotePagesParentNotebookSectionGroupsOperations
from .operations import UsersOnenotePagesParentNotebookSectionGroupsSectionsOperations
from .operations import UsersOnenotePagesParentNotebookSectionsOperations
from .operations import UsersOnenotePagesParentNotebookSectionsParentSectionGroupOperations
from .operations import UsersOnenotePagesParentSectionOperations
from .operations import UsersOnenotePagesParentSectionParentNotebookOperations
from .operations import UsersOnenotePagesParentSectionParentNotebookSectionGroupsOperations
from .operations import UsersOnenotePagesParentSectionParentSectionGroupOperations
from .operations import UsersOnenotePagesParentSectionParentSectionGroupParentNotebookOperations
from .operations import UsersOnenoteSectionGroupsOperations
from .operations import UsersOnenoteSectionGroupsParentNotebookOperations
from .operations import UsersOnenoteSectionGroupsParentNotebookSectionsOperations
from .operations import UsersOnenoteSectionGroupsParentNotebookSectionsPagesOperations
from .operations import UsersOnenoteSectionGroupsSectionsOperations
from .operations import UsersOnenoteSectionGroupsSectionsPagesOperations
from .operations import UsersOnenoteSectionGroupsSectionsPagesParentNotebookOperations
from .operations import UsersOnenoteSectionGroupsSectionsParentNotebookOperations
from .operations import UsersOnenoteSectionsOperations
from .operations import UsersOnenoteSectionsPagesOperations
from .operations import UsersOnenoteSectionsPagesParentNotebookOperations
from .operations import UsersOnenoteSectionsPagesParentNotebookSectionGroupsOperations
from .operations import UsersOnenoteSectionsParentNotebookOperations
from .operations import UsersOnenoteSectionsParentNotebookSectionGroupsOperations
from .operations import UsersOnenoteSectionsParentSectionGroupOperations
from .operations import UsersOnenoteSectionsParentSectionGroupParentNotebookOperations
from .. import models


class Notes(object):
    """Notes.

    :ivar groups: GroupsOperations operations
    :vartype groups: notes.aio.operations.GroupsOperations
    :ivar groups_onenote: GroupsOnenoteOperations operations
    :vartype groups_onenote: notes.aio.operations.GroupsOnenoteOperations
    :ivar groups_onenote_notebooks: GroupsOnenoteNotebooksOperations operations
    :vartype groups_onenote_notebooks: notes.aio.operations.GroupsOnenoteNotebooksOperations
    :ivar groups_onenote_notebooks_section_groups: GroupsOnenoteNotebooksSectionGroupsOperations operations
    :vartype groups_onenote_notebooks_section_groups: notes.aio.operations.GroupsOnenoteNotebooksSectionGroupsOperations
    :ivar groups_onenote_notebooks_section_groups_sections: GroupsOnenoteNotebooksSectionGroupsSectionsOperations operations
    :vartype groups_onenote_notebooks_section_groups_sections: notes.aio.operations.GroupsOnenoteNotebooksSectionGroupsSectionsOperations
    :ivar groups_onenote_notebooks_section_groups_sections_pages: GroupsOnenoteNotebooksSectionGroupsSectionsPagesOperations operations
    :vartype groups_onenote_notebooks_section_groups_sections_pages: notes.aio.operations.GroupsOnenoteNotebooksSectionGroupsSectionsPagesOperations
    :ivar groups_onenote_notebooks_sections: GroupsOnenoteNotebooksSectionsOperations operations
    :vartype groups_onenote_notebooks_sections: notes.aio.operations.GroupsOnenoteNotebooksSectionsOperations
    :ivar groups_onenote_notebooks_sections_pages: GroupsOnenoteNotebooksSectionsPagesOperations operations
    :vartype groups_onenote_notebooks_sections_pages: notes.aio.operations.GroupsOnenoteNotebooksSectionsPagesOperations
    :ivar groups_onenote_notebooks_sections_parent_section_group: GroupsOnenoteNotebooksSectionsParentSectionGroupOperations operations
    :vartype groups_onenote_notebooks_sections_parent_section_group: notes.aio.operations.GroupsOnenoteNotebooksSectionsParentSectionGroupOperations
    :ivar groups_onenote_pages: GroupsOnenotePagesOperations operations
    :vartype groups_onenote_pages: notes.aio.operations.GroupsOnenotePagesOperations
    :ivar groups_onenote_pages_parent_notebook: GroupsOnenotePagesParentNotebookOperations operations
    :vartype groups_onenote_pages_parent_notebook: notes.aio.operations.GroupsOnenotePagesParentNotebookOperations
    :ivar groups_onenote_pages_parent_notebook_section_groups: GroupsOnenotePagesParentNotebookSectionGroupsOperations operations
    :vartype groups_onenote_pages_parent_notebook_section_groups: notes.aio.operations.GroupsOnenotePagesParentNotebookSectionGroupsOperations
    :ivar groups_onenote_pages_parent_notebook_section_groups_sections: GroupsOnenotePagesParentNotebookSectionGroupsSectionsOperations operations
    :vartype groups_onenote_pages_parent_notebook_section_groups_sections: notes.aio.operations.GroupsOnenotePagesParentNotebookSectionGroupsSectionsOperations
    :ivar groups_onenote_pages_parent_notebook_sections: GroupsOnenotePagesParentNotebookSectionsOperations operations
    :vartype groups_onenote_pages_parent_notebook_sections: notes.aio.operations.GroupsOnenotePagesParentNotebookSectionsOperations
    :ivar groups_onenote_pages_parent_notebook_sections_parent_section_group: GroupsOnenotePagesParentNotebookSectionsParentSectionGroupOperations operations
    :vartype groups_onenote_pages_parent_notebook_sections_parent_section_group: notes.aio.operations.GroupsOnenotePagesParentNotebookSectionsParentSectionGroupOperations
    :ivar groups_onenote_pages_parent_section: GroupsOnenotePagesParentSectionOperations operations
    :vartype groups_onenote_pages_parent_section: notes.aio.operations.GroupsOnenotePagesParentSectionOperations
    :ivar groups_onenote_pages_parent_section_parent_notebook: GroupsOnenotePagesParentSectionParentNotebookOperations operations
    :vartype groups_onenote_pages_parent_section_parent_notebook: notes.aio.operations.GroupsOnenotePagesParentSectionParentNotebookOperations
    :ivar groups_onenote_pages_parent_section_parent_notebook_section_groups: GroupsOnenotePagesParentSectionParentNotebookSectionGroupsOperations operations
    :vartype groups_onenote_pages_parent_section_parent_notebook_section_groups: notes.aio.operations.GroupsOnenotePagesParentSectionParentNotebookSectionGroupsOperations
    :ivar groups_onenote_pages_parent_section_parent_section_group: GroupsOnenotePagesParentSectionParentSectionGroupOperations operations
    :vartype groups_onenote_pages_parent_section_parent_section_group: notes.aio.operations.GroupsOnenotePagesParentSectionParentSectionGroupOperations
    :ivar groups_onenote_pages_parent_section_parent_section_group_parent_notebook: GroupsOnenotePagesParentSectionParentSectionGroupParentNotebookOperations operations
    :vartype groups_onenote_pages_parent_section_parent_section_group_parent_notebook: notes.aio.operations.GroupsOnenotePagesParentSectionParentSectionGroupParentNotebookOperations
    :ivar groups_onenote_section_groups: GroupsOnenoteSectionGroupsOperations operations
    :vartype groups_onenote_section_groups: notes.aio.operations.GroupsOnenoteSectionGroupsOperations
    :ivar groups_onenote_section_groups_parent_notebook: GroupsOnenoteSectionGroupsParentNotebookOperations operations
    :vartype groups_onenote_section_groups_parent_notebook: notes.aio.operations.GroupsOnenoteSectionGroupsParentNotebookOperations
    :ivar groups_onenote_section_groups_parent_notebook_sections: GroupsOnenoteSectionGroupsParentNotebookSectionsOperations operations
    :vartype groups_onenote_section_groups_parent_notebook_sections: notes.aio.operations.GroupsOnenoteSectionGroupsParentNotebookSectionsOperations
    :ivar groups_onenote_section_groups_parent_notebook_sections_pages: GroupsOnenoteSectionGroupsParentNotebookSectionsPagesOperations operations
    :vartype groups_onenote_section_groups_parent_notebook_sections_pages: notes.aio.operations.GroupsOnenoteSectionGroupsParentNotebookSectionsPagesOperations
    :ivar groups_onenote_section_groups_sections: GroupsOnenoteSectionGroupsSectionsOperations operations
    :vartype groups_onenote_section_groups_sections: notes.aio.operations.GroupsOnenoteSectionGroupsSectionsOperations
    :ivar groups_onenote_section_groups_sections_pages: GroupsOnenoteSectionGroupsSectionsPagesOperations operations
    :vartype groups_onenote_section_groups_sections_pages: notes.aio.operations.GroupsOnenoteSectionGroupsSectionsPagesOperations
    :ivar groups_onenote_section_groups_sections_pages_parent_notebook: GroupsOnenoteSectionGroupsSectionsPagesParentNotebookOperations operations
    :vartype groups_onenote_section_groups_sections_pages_parent_notebook: notes.aio.operations.GroupsOnenoteSectionGroupsSectionsPagesParentNotebookOperations
    :ivar groups_onenote_section_groups_sections_parent_notebook: GroupsOnenoteSectionGroupsSectionsParentNotebookOperations operations
    :vartype groups_onenote_section_groups_sections_parent_notebook: notes.aio.operations.GroupsOnenoteSectionGroupsSectionsParentNotebookOperations
    :ivar groups_onenote_sections: GroupsOnenoteSectionsOperations operations
    :vartype groups_onenote_sections: notes.aio.operations.GroupsOnenoteSectionsOperations
    :ivar groups_onenote_sections_pages: GroupsOnenoteSectionsPagesOperations operations
    :vartype groups_onenote_sections_pages: notes.aio.operations.GroupsOnenoteSectionsPagesOperations
    :ivar groups_onenote_sections_pages_parent_notebook: GroupsOnenoteSectionsPagesParentNotebookOperations operations
    :vartype groups_onenote_sections_pages_parent_notebook: notes.aio.operations.GroupsOnenoteSectionsPagesParentNotebookOperations
    :ivar groups_onenote_sections_pages_parent_notebook_section_groups: GroupsOnenoteSectionsPagesParentNotebookSectionGroupsOperations operations
    :vartype groups_onenote_sections_pages_parent_notebook_section_groups: notes.aio.operations.GroupsOnenoteSectionsPagesParentNotebookSectionGroupsOperations
    :ivar groups_onenote_sections_parent_notebook: GroupsOnenoteSectionsParentNotebookOperations operations
    :vartype groups_onenote_sections_parent_notebook: notes.aio.operations.GroupsOnenoteSectionsParentNotebookOperations
    :ivar groups_onenote_sections_parent_notebook_section_groups: GroupsOnenoteSectionsParentNotebookSectionGroupsOperations operations
    :vartype groups_onenote_sections_parent_notebook_section_groups: notes.aio.operations.GroupsOnenoteSectionsParentNotebookSectionGroupsOperations
    :ivar groups_onenote_sections_parent_section_group: GroupsOnenoteSectionsParentSectionGroupOperations operations
    :vartype groups_onenote_sections_parent_section_group: notes.aio.operations.GroupsOnenoteSectionsParentSectionGroupOperations
    :ivar groups_onenote_sections_parent_section_group_parent_notebook: GroupsOnenoteSectionsParentSectionGroupParentNotebookOperations operations
    :vartype groups_onenote_sections_parent_section_group_parent_notebook: notes.aio.operations.GroupsOnenoteSectionsParentSectionGroupParentNotebookOperations
    :ivar sites: SitesOperations operations
    :vartype sites: notes.aio.operations.SitesOperations
    :ivar sites_onenote: SitesOnenoteOperations operations
    :vartype sites_onenote: notes.aio.operations.SitesOnenoteOperations
    :ivar sites_onenote_notebooks: SitesOnenoteNotebooksOperations operations
    :vartype sites_onenote_notebooks: notes.aio.operations.SitesOnenoteNotebooksOperations
    :ivar sites_onenote_notebooks_section_groups: SitesOnenoteNotebooksSectionGroupsOperations operations
    :vartype sites_onenote_notebooks_section_groups: notes.aio.operations.SitesOnenoteNotebooksSectionGroupsOperations
    :ivar sites_onenote_notebooks_section_groups_sections: SitesOnenoteNotebooksSectionGroupsSectionsOperations operations
    :vartype sites_onenote_notebooks_section_groups_sections: notes.aio.operations.SitesOnenoteNotebooksSectionGroupsSectionsOperations
    :ivar sites_onenote_notebooks_section_groups_sections_pages: SitesOnenoteNotebooksSectionGroupsSectionsPagesOperations operations
    :vartype sites_onenote_notebooks_section_groups_sections_pages: notes.aio.operations.SitesOnenoteNotebooksSectionGroupsSectionsPagesOperations
    :ivar sites_onenote_notebooks_sections: SitesOnenoteNotebooksSectionsOperations operations
    :vartype sites_onenote_notebooks_sections: notes.aio.operations.SitesOnenoteNotebooksSectionsOperations
    :ivar sites_onenote_notebooks_sections_pages: SitesOnenoteNotebooksSectionsPagesOperations operations
    :vartype sites_onenote_notebooks_sections_pages: notes.aio.operations.SitesOnenoteNotebooksSectionsPagesOperations
    :ivar sites_onenote_notebooks_sections_parent_section_group: SitesOnenoteNotebooksSectionsParentSectionGroupOperations operations
    :vartype sites_onenote_notebooks_sections_parent_section_group: notes.aio.operations.SitesOnenoteNotebooksSectionsParentSectionGroupOperations
    :ivar sites_onenote_pages: SitesOnenotePagesOperations operations
    :vartype sites_onenote_pages: notes.aio.operations.SitesOnenotePagesOperations
    :ivar sites_onenote_pages_parent_notebook: SitesOnenotePagesParentNotebookOperations operations
    :vartype sites_onenote_pages_parent_notebook: notes.aio.operations.SitesOnenotePagesParentNotebookOperations
    :ivar sites_onenote_pages_parent_notebook_section_groups: SitesOnenotePagesParentNotebookSectionGroupsOperations operations
    :vartype sites_onenote_pages_parent_notebook_section_groups: notes.aio.operations.SitesOnenotePagesParentNotebookSectionGroupsOperations
    :ivar sites_onenote_pages_parent_notebook_section_groups_sections: SitesOnenotePagesParentNotebookSectionGroupsSectionsOperations operations
    :vartype sites_onenote_pages_parent_notebook_section_groups_sections: notes.aio.operations.SitesOnenotePagesParentNotebookSectionGroupsSectionsOperations
    :ivar sites_onenote_pages_parent_notebook_sections: SitesOnenotePagesParentNotebookSectionsOperations operations
    :vartype sites_onenote_pages_parent_notebook_sections: notes.aio.operations.SitesOnenotePagesParentNotebookSectionsOperations
    :ivar sites_onenote_pages_parent_notebook_sections_parent_section_group: SitesOnenotePagesParentNotebookSectionsParentSectionGroupOperations operations
    :vartype sites_onenote_pages_parent_notebook_sections_parent_section_group: notes.aio.operations.SitesOnenotePagesParentNotebookSectionsParentSectionGroupOperations
    :ivar sites_onenote_pages_parent_section: SitesOnenotePagesParentSectionOperations operations
    :vartype sites_onenote_pages_parent_section: notes.aio.operations.SitesOnenotePagesParentSectionOperations
    :ivar sites_onenote_pages_parent_section_parent_notebook: SitesOnenotePagesParentSectionParentNotebookOperations operations
    :vartype sites_onenote_pages_parent_section_parent_notebook: notes.aio.operations.SitesOnenotePagesParentSectionParentNotebookOperations
    :ivar sites_onenote_pages_parent_section_parent_notebook_section_groups: SitesOnenotePagesParentSectionParentNotebookSectionGroupsOperations operations
    :vartype sites_onenote_pages_parent_section_parent_notebook_section_groups: notes.aio.operations.SitesOnenotePagesParentSectionParentNotebookSectionGroupsOperations
    :ivar sites_onenote_pages_parent_section_parent_section_group: SitesOnenotePagesParentSectionParentSectionGroupOperations operations
    :vartype sites_onenote_pages_parent_section_parent_section_group: notes.aio.operations.SitesOnenotePagesParentSectionParentSectionGroupOperations
    :ivar sites_onenote_pages_parent_section_parent_section_group_parent_notebook: SitesOnenotePagesParentSectionParentSectionGroupParentNotebookOperations operations
    :vartype sites_onenote_pages_parent_section_parent_section_group_parent_notebook: notes.aio.operations.SitesOnenotePagesParentSectionParentSectionGroupParentNotebookOperations
    :ivar sites_onenote_section_groups: SitesOnenoteSectionGroupsOperations operations
    :vartype sites_onenote_section_groups: notes.aio.operations.SitesOnenoteSectionGroupsOperations
    :ivar sites_onenote_section_groups_parent_notebook: SitesOnenoteSectionGroupsParentNotebookOperations operations
    :vartype sites_onenote_section_groups_parent_notebook: notes.aio.operations.SitesOnenoteSectionGroupsParentNotebookOperations
    :ivar sites_onenote_section_groups_parent_notebook_sections: SitesOnenoteSectionGroupsParentNotebookSectionsOperations operations
    :vartype sites_onenote_section_groups_parent_notebook_sections: notes.aio.operations.SitesOnenoteSectionGroupsParentNotebookSectionsOperations
    :ivar sites_onenote_section_groups_parent_notebook_sections_pages: SitesOnenoteSectionGroupsParentNotebookSectionsPagesOperations operations
    :vartype sites_onenote_section_groups_parent_notebook_sections_pages: notes.aio.operations.SitesOnenoteSectionGroupsParentNotebookSectionsPagesOperations
    :ivar sites_onenote_section_groups_sections: SitesOnenoteSectionGroupsSectionsOperations operations
    :vartype sites_onenote_section_groups_sections: notes.aio.operations.SitesOnenoteSectionGroupsSectionsOperations
    :ivar sites_onenote_section_groups_sections_pages: SitesOnenoteSectionGroupsSectionsPagesOperations operations
    :vartype sites_onenote_section_groups_sections_pages: notes.aio.operations.SitesOnenoteSectionGroupsSectionsPagesOperations
    :ivar sites_onenote_section_groups_sections_pages_parent_notebook: SitesOnenoteSectionGroupsSectionsPagesParentNotebookOperations operations
    :vartype sites_onenote_section_groups_sections_pages_parent_notebook: notes.aio.operations.SitesOnenoteSectionGroupsSectionsPagesParentNotebookOperations
    :ivar sites_onenote_section_groups_sections_parent_notebook: SitesOnenoteSectionGroupsSectionsParentNotebookOperations operations
    :vartype sites_onenote_section_groups_sections_parent_notebook: notes.aio.operations.SitesOnenoteSectionGroupsSectionsParentNotebookOperations
    :ivar sites_onenote_sections: SitesOnenoteSectionsOperations operations
    :vartype sites_onenote_sections: notes.aio.operations.SitesOnenoteSectionsOperations
    :ivar sites_onenote_sections_pages: SitesOnenoteSectionsPagesOperations operations
    :vartype sites_onenote_sections_pages: notes.aio.operations.SitesOnenoteSectionsPagesOperations
    :ivar sites_onenote_sections_pages_parent_notebook: SitesOnenoteSectionsPagesParentNotebookOperations operations
    :vartype sites_onenote_sections_pages_parent_notebook: notes.aio.operations.SitesOnenoteSectionsPagesParentNotebookOperations
    :ivar sites_onenote_sections_pages_parent_notebook_section_groups: SitesOnenoteSectionsPagesParentNotebookSectionGroupsOperations operations
    :vartype sites_onenote_sections_pages_parent_notebook_section_groups: notes.aio.operations.SitesOnenoteSectionsPagesParentNotebookSectionGroupsOperations
    :ivar sites_onenote_sections_parent_notebook: SitesOnenoteSectionsParentNotebookOperations operations
    :vartype sites_onenote_sections_parent_notebook: notes.aio.operations.SitesOnenoteSectionsParentNotebookOperations
    :ivar sites_onenote_sections_parent_notebook_section_groups: SitesOnenoteSectionsParentNotebookSectionGroupsOperations operations
    :vartype sites_onenote_sections_parent_notebook_section_groups: notes.aio.operations.SitesOnenoteSectionsParentNotebookSectionGroupsOperations
    :ivar sites_onenote_sections_parent_section_group: SitesOnenoteSectionsParentSectionGroupOperations operations
    :vartype sites_onenote_sections_parent_section_group: notes.aio.operations.SitesOnenoteSectionsParentSectionGroupOperations
    :ivar sites_onenote_sections_parent_section_group_parent_notebook: SitesOnenoteSectionsParentSectionGroupParentNotebookOperations operations
    :vartype sites_onenote_sections_parent_section_group_parent_notebook: notes.aio.operations.SitesOnenoteSectionsParentSectionGroupParentNotebookOperations
    :ivar users: UsersOperations operations
    :vartype users: notes.aio.operations.UsersOperations
    :ivar users_onenote: UsersOnenoteOperations operations
    :vartype users_onenote: notes.aio.operations.UsersOnenoteOperations
    :ivar users_onenote_notebooks: UsersOnenoteNotebooksOperations operations
    :vartype users_onenote_notebooks: notes.aio.operations.UsersOnenoteNotebooksOperations
    :ivar users_onenote_notebooks_section_groups: UsersOnenoteNotebooksSectionGroupsOperations operations
    :vartype users_onenote_notebooks_section_groups: notes.aio.operations.UsersOnenoteNotebooksSectionGroupsOperations
    :ivar users_onenote_notebooks_section_groups_sections: UsersOnenoteNotebooksSectionGroupsSectionsOperations operations
    :vartype users_onenote_notebooks_section_groups_sections: notes.aio.operations.UsersOnenoteNotebooksSectionGroupsSectionsOperations
    :ivar users_onenote_notebooks_section_groups_sections_pages: UsersOnenoteNotebooksSectionGroupsSectionsPagesOperations operations
    :vartype users_onenote_notebooks_section_groups_sections_pages: notes.aio.operations.UsersOnenoteNotebooksSectionGroupsSectionsPagesOperations
    :ivar users_onenote_notebooks_sections: UsersOnenoteNotebooksSectionsOperations operations
    :vartype users_onenote_notebooks_sections: notes.aio.operations.UsersOnenoteNotebooksSectionsOperations
    :ivar users_onenote_notebooks_sections_pages: UsersOnenoteNotebooksSectionsPagesOperations operations
    :vartype users_onenote_notebooks_sections_pages: notes.aio.operations.UsersOnenoteNotebooksSectionsPagesOperations
    :ivar users_onenote_notebooks_sections_parent_section_group: UsersOnenoteNotebooksSectionsParentSectionGroupOperations operations
    :vartype users_onenote_notebooks_sections_parent_section_group: notes.aio.operations.UsersOnenoteNotebooksSectionsParentSectionGroupOperations
    :ivar users_onenote_pages: UsersOnenotePagesOperations operations
    :vartype users_onenote_pages: notes.aio.operations.UsersOnenotePagesOperations
    :ivar users_onenote_pages_parent_notebook: UsersOnenotePagesParentNotebookOperations operations
    :vartype users_onenote_pages_parent_notebook: notes.aio.operations.UsersOnenotePagesParentNotebookOperations
    :ivar users_onenote_pages_parent_notebook_section_groups: UsersOnenotePagesParentNotebookSectionGroupsOperations operations
    :vartype users_onenote_pages_parent_notebook_section_groups: notes.aio.operations.UsersOnenotePagesParentNotebookSectionGroupsOperations
    :ivar users_onenote_pages_parent_notebook_section_groups_sections: UsersOnenotePagesParentNotebookSectionGroupsSectionsOperations operations
    :vartype users_onenote_pages_parent_notebook_section_groups_sections: notes.aio.operations.UsersOnenotePagesParentNotebookSectionGroupsSectionsOperations
    :ivar users_onenote_pages_parent_notebook_sections: UsersOnenotePagesParentNotebookSectionsOperations operations
    :vartype users_onenote_pages_parent_notebook_sections: notes.aio.operations.UsersOnenotePagesParentNotebookSectionsOperations
    :ivar users_onenote_pages_parent_notebook_sections_parent_section_group: UsersOnenotePagesParentNotebookSectionsParentSectionGroupOperations operations
    :vartype users_onenote_pages_parent_notebook_sections_parent_section_group: notes.aio.operations.UsersOnenotePagesParentNotebookSectionsParentSectionGroupOperations
    :ivar users_onenote_pages_parent_section: UsersOnenotePagesParentSectionOperations operations
    :vartype users_onenote_pages_parent_section: notes.aio.operations.UsersOnenotePagesParentSectionOperations
    :ivar users_onenote_pages_parent_section_parent_notebook: UsersOnenotePagesParentSectionParentNotebookOperations operations
    :vartype users_onenote_pages_parent_section_parent_notebook: notes.aio.operations.UsersOnenotePagesParentSectionParentNotebookOperations
    :ivar users_onenote_pages_parent_section_parent_notebook_section_groups: UsersOnenotePagesParentSectionParentNotebookSectionGroupsOperations operations
    :vartype users_onenote_pages_parent_section_parent_notebook_section_groups: notes.aio.operations.UsersOnenotePagesParentSectionParentNotebookSectionGroupsOperations
    :ivar users_onenote_pages_parent_section_parent_section_group: UsersOnenotePagesParentSectionParentSectionGroupOperations operations
    :vartype users_onenote_pages_parent_section_parent_section_group: notes.aio.operations.UsersOnenotePagesParentSectionParentSectionGroupOperations
    :ivar users_onenote_pages_parent_section_parent_section_group_parent_notebook: UsersOnenotePagesParentSectionParentSectionGroupParentNotebookOperations operations
    :vartype users_onenote_pages_parent_section_parent_section_group_parent_notebook: notes.aio.operations.UsersOnenotePagesParentSectionParentSectionGroupParentNotebookOperations
    :ivar users_onenote_section_groups: UsersOnenoteSectionGroupsOperations operations
    :vartype users_onenote_section_groups: notes.aio.operations.UsersOnenoteSectionGroupsOperations
    :ivar users_onenote_section_groups_parent_notebook: UsersOnenoteSectionGroupsParentNotebookOperations operations
    :vartype users_onenote_section_groups_parent_notebook: notes.aio.operations.UsersOnenoteSectionGroupsParentNotebookOperations
    :ivar users_onenote_section_groups_parent_notebook_sections: UsersOnenoteSectionGroupsParentNotebookSectionsOperations operations
    :vartype users_onenote_section_groups_parent_notebook_sections: notes.aio.operations.UsersOnenoteSectionGroupsParentNotebookSectionsOperations
    :ivar users_onenote_section_groups_parent_notebook_sections_pages: UsersOnenoteSectionGroupsParentNotebookSectionsPagesOperations operations
    :vartype users_onenote_section_groups_parent_notebook_sections_pages: notes.aio.operations.UsersOnenoteSectionGroupsParentNotebookSectionsPagesOperations
    :ivar users_onenote_section_groups_sections: UsersOnenoteSectionGroupsSectionsOperations operations
    :vartype users_onenote_section_groups_sections: notes.aio.operations.UsersOnenoteSectionGroupsSectionsOperations
    :ivar users_onenote_section_groups_sections_pages: UsersOnenoteSectionGroupsSectionsPagesOperations operations
    :vartype users_onenote_section_groups_sections_pages: notes.aio.operations.UsersOnenoteSectionGroupsSectionsPagesOperations
    :ivar users_onenote_section_groups_sections_pages_parent_notebook: UsersOnenoteSectionGroupsSectionsPagesParentNotebookOperations operations
    :vartype users_onenote_section_groups_sections_pages_parent_notebook: notes.aio.operations.UsersOnenoteSectionGroupsSectionsPagesParentNotebookOperations
    :ivar users_onenote_section_groups_sections_parent_notebook: UsersOnenoteSectionGroupsSectionsParentNotebookOperations operations
    :vartype users_onenote_section_groups_sections_parent_notebook: notes.aio.operations.UsersOnenoteSectionGroupsSectionsParentNotebookOperations
    :ivar users_onenote_sections: UsersOnenoteSectionsOperations operations
    :vartype users_onenote_sections: notes.aio.operations.UsersOnenoteSectionsOperations
    :ivar users_onenote_sections_pages: UsersOnenoteSectionsPagesOperations operations
    :vartype users_onenote_sections_pages: notes.aio.operations.UsersOnenoteSectionsPagesOperations
    :ivar users_onenote_sections_pages_parent_notebook: UsersOnenoteSectionsPagesParentNotebookOperations operations
    :vartype users_onenote_sections_pages_parent_notebook: notes.aio.operations.UsersOnenoteSectionsPagesParentNotebookOperations
    :ivar users_onenote_sections_pages_parent_notebook_section_groups: UsersOnenoteSectionsPagesParentNotebookSectionGroupsOperations operations
    :vartype users_onenote_sections_pages_parent_notebook_section_groups: notes.aio.operations.UsersOnenoteSectionsPagesParentNotebookSectionGroupsOperations
    :ivar users_onenote_sections_parent_notebook: UsersOnenoteSectionsParentNotebookOperations operations
    :vartype users_onenote_sections_parent_notebook: notes.aio.operations.UsersOnenoteSectionsParentNotebookOperations
    :ivar users_onenote_sections_parent_notebook_section_groups: UsersOnenoteSectionsParentNotebookSectionGroupsOperations operations
    :vartype users_onenote_sections_parent_notebook_section_groups: notes.aio.operations.UsersOnenoteSectionsParentNotebookSectionGroupsOperations
    :ivar users_onenote_sections_parent_section_group: UsersOnenoteSectionsParentSectionGroupOperations operations
    :vartype users_onenote_sections_parent_section_group: notes.aio.operations.UsersOnenoteSectionsParentSectionGroupOperations
    :ivar users_onenote_sections_parent_section_group_parent_notebook: UsersOnenoteSectionsParentSectionGroupParentNotebookOperations operations
    :vartype users_onenote_sections_parent_section_group_parent_notebook: notes.aio.operations.UsersOnenoteSectionsParentSectionGroupParentNotebookOperations
    :param credential: Credential needed for the client to connect to Azure.
    :type credential: ~azure.core.credentials_async.AsyncTokenCredential
    :param top: Show only the first n items.
    :type top: int
    :param skip: Skip the first n items.
    :type skip: int
    :param search: Search items by search phrases.
    :type search: str
    :param filter: Filter items by property values.
    :type filter: str
    :param count: Include count of items.
    :type count: bool
    :param str base_url: Service URL
    """

    def __init__(
        self,
        credential: "AsyncTokenCredential",
        top: Optional[int] = None,
        skip: Optional[int] = None,
        search: Optional[str] = None,
        filter: Optional[str] = None,
        count: Optional[bool] = None,
        base_url: Optional[str] = None,
        **kwargs: Any
    ) -> None:
        if not base_url:
            base_url = 'https://graph.microsoft.com/v1.0'
        self._config = NotesConfiguration(credential, top, skip, search, filter, count, **kwargs)
        self._client = AsyncARMPipelineClient(base_url=base_url, config=self._config, **kwargs)

        client_models = {k: v for k, v in models.__dict__.items() if isinstance(v, type)}
        self._serialize = Serializer(client_models)
        self._serialize.client_side_validation = False
        self._deserialize = Deserializer(client_models)

        self.groups = GroupsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.groups_onenote = GroupsOnenoteOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.groups_onenote_notebooks = GroupsOnenoteNotebooksOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.groups_onenote_notebooks_section_groups = GroupsOnenoteNotebooksSectionGroupsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.groups_onenote_notebooks_section_groups_sections = GroupsOnenoteNotebooksSectionGroupsSectionsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.groups_onenote_notebooks_section_groups_sections_pages = GroupsOnenoteNotebooksSectionGroupsSectionsPagesOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.groups_onenote_notebooks_sections = GroupsOnenoteNotebooksSectionsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.groups_onenote_notebooks_sections_pages = GroupsOnenoteNotebooksSectionsPagesOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.groups_onenote_notebooks_sections_parent_section_group = GroupsOnenoteNotebooksSectionsParentSectionGroupOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.groups_onenote_pages = GroupsOnenotePagesOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.groups_onenote_pages_parent_notebook = GroupsOnenotePagesParentNotebookOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.groups_onenote_pages_parent_notebook_section_groups = GroupsOnenotePagesParentNotebookSectionGroupsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.groups_onenote_pages_parent_notebook_section_groups_sections = GroupsOnenotePagesParentNotebookSectionGroupsSectionsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.groups_onenote_pages_parent_notebook_sections = GroupsOnenotePagesParentNotebookSectionsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.groups_onenote_pages_parent_notebook_sections_parent_section_group = GroupsOnenotePagesParentNotebookSectionsParentSectionGroupOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.groups_onenote_pages_parent_section = GroupsOnenotePagesParentSectionOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.groups_onenote_pages_parent_section_parent_notebook = GroupsOnenotePagesParentSectionParentNotebookOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.groups_onenote_pages_parent_section_parent_notebook_section_groups = GroupsOnenotePagesParentSectionParentNotebookSectionGroupsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.groups_onenote_pages_parent_section_parent_section_group = GroupsOnenotePagesParentSectionParentSectionGroupOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.groups_onenote_pages_parent_section_parent_section_group_parent_notebook = GroupsOnenotePagesParentSectionParentSectionGroupParentNotebookOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.groups_onenote_section_groups = GroupsOnenoteSectionGroupsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.groups_onenote_section_groups_parent_notebook = GroupsOnenoteSectionGroupsParentNotebookOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.groups_onenote_section_groups_parent_notebook_sections = GroupsOnenoteSectionGroupsParentNotebookSectionsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.groups_onenote_section_groups_parent_notebook_sections_pages = GroupsOnenoteSectionGroupsParentNotebookSectionsPagesOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.groups_onenote_section_groups_sections = GroupsOnenoteSectionGroupsSectionsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.groups_onenote_section_groups_sections_pages = GroupsOnenoteSectionGroupsSectionsPagesOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.groups_onenote_section_groups_sections_pages_parent_notebook = GroupsOnenoteSectionGroupsSectionsPagesParentNotebookOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.groups_onenote_section_groups_sections_parent_notebook = GroupsOnenoteSectionGroupsSectionsParentNotebookOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.groups_onenote_sections = GroupsOnenoteSectionsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.groups_onenote_sections_pages = GroupsOnenoteSectionsPagesOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.groups_onenote_sections_pages_parent_notebook = GroupsOnenoteSectionsPagesParentNotebookOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.groups_onenote_sections_pages_parent_notebook_section_groups = GroupsOnenoteSectionsPagesParentNotebookSectionGroupsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.groups_onenote_sections_parent_notebook = GroupsOnenoteSectionsParentNotebookOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.groups_onenote_sections_parent_notebook_section_groups = GroupsOnenoteSectionsParentNotebookSectionGroupsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.groups_onenote_sections_parent_section_group = GroupsOnenoteSectionsParentSectionGroupOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.groups_onenote_sections_parent_section_group_parent_notebook = GroupsOnenoteSectionsParentSectionGroupParentNotebookOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.sites = SitesOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.sites_onenote = SitesOnenoteOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.sites_onenote_notebooks = SitesOnenoteNotebooksOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.sites_onenote_notebooks_section_groups = SitesOnenoteNotebooksSectionGroupsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.sites_onenote_notebooks_section_groups_sections = SitesOnenoteNotebooksSectionGroupsSectionsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.sites_onenote_notebooks_section_groups_sections_pages = SitesOnenoteNotebooksSectionGroupsSectionsPagesOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.sites_onenote_notebooks_sections = SitesOnenoteNotebooksSectionsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.sites_onenote_notebooks_sections_pages = SitesOnenoteNotebooksSectionsPagesOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.sites_onenote_notebooks_sections_parent_section_group = SitesOnenoteNotebooksSectionsParentSectionGroupOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.sites_onenote_pages = SitesOnenotePagesOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.sites_onenote_pages_parent_notebook = SitesOnenotePagesParentNotebookOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.sites_onenote_pages_parent_notebook_section_groups = SitesOnenotePagesParentNotebookSectionGroupsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.sites_onenote_pages_parent_notebook_section_groups_sections = SitesOnenotePagesParentNotebookSectionGroupsSectionsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.sites_onenote_pages_parent_notebook_sections = SitesOnenotePagesParentNotebookSectionsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.sites_onenote_pages_parent_notebook_sections_parent_section_group = SitesOnenotePagesParentNotebookSectionsParentSectionGroupOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.sites_onenote_pages_parent_section = SitesOnenotePagesParentSectionOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.sites_onenote_pages_parent_section_parent_notebook = SitesOnenotePagesParentSectionParentNotebookOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.sites_onenote_pages_parent_section_parent_notebook_section_groups = SitesOnenotePagesParentSectionParentNotebookSectionGroupsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.sites_onenote_pages_parent_section_parent_section_group = SitesOnenotePagesParentSectionParentSectionGroupOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.sites_onenote_pages_parent_section_parent_section_group_parent_notebook = SitesOnenotePagesParentSectionParentSectionGroupParentNotebookOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.sites_onenote_section_groups = SitesOnenoteSectionGroupsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.sites_onenote_section_groups_parent_notebook = SitesOnenoteSectionGroupsParentNotebookOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.sites_onenote_section_groups_parent_notebook_sections = SitesOnenoteSectionGroupsParentNotebookSectionsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.sites_onenote_section_groups_parent_notebook_sections_pages = SitesOnenoteSectionGroupsParentNotebookSectionsPagesOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.sites_onenote_section_groups_sections = SitesOnenoteSectionGroupsSectionsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.sites_onenote_section_groups_sections_pages = SitesOnenoteSectionGroupsSectionsPagesOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.sites_onenote_section_groups_sections_pages_parent_notebook = SitesOnenoteSectionGroupsSectionsPagesParentNotebookOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.sites_onenote_section_groups_sections_parent_notebook = SitesOnenoteSectionGroupsSectionsParentNotebookOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.sites_onenote_sections = SitesOnenoteSectionsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.sites_onenote_sections_pages = SitesOnenoteSectionsPagesOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.sites_onenote_sections_pages_parent_notebook = SitesOnenoteSectionsPagesParentNotebookOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.sites_onenote_sections_pages_parent_notebook_section_groups = SitesOnenoteSectionsPagesParentNotebookSectionGroupsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.sites_onenote_sections_parent_notebook = SitesOnenoteSectionsParentNotebookOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.sites_onenote_sections_parent_notebook_section_groups = SitesOnenoteSectionsParentNotebookSectionGroupsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.sites_onenote_sections_parent_section_group = SitesOnenoteSectionsParentSectionGroupOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.sites_onenote_sections_parent_section_group_parent_notebook = SitesOnenoteSectionsParentSectionGroupParentNotebookOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.users = UsersOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.users_onenote = UsersOnenoteOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.users_onenote_notebooks = UsersOnenoteNotebooksOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.users_onenote_notebooks_section_groups = UsersOnenoteNotebooksSectionGroupsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.users_onenote_notebooks_section_groups_sections = UsersOnenoteNotebooksSectionGroupsSectionsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.users_onenote_notebooks_section_groups_sections_pages = UsersOnenoteNotebooksSectionGroupsSectionsPagesOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.users_onenote_notebooks_sections = UsersOnenoteNotebooksSectionsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.users_onenote_notebooks_sections_pages = UsersOnenoteNotebooksSectionsPagesOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.users_onenote_notebooks_sections_parent_section_group = UsersOnenoteNotebooksSectionsParentSectionGroupOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.users_onenote_pages = UsersOnenotePagesOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.users_onenote_pages_parent_notebook = UsersOnenotePagesParentNotebookOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.users_onenote_pages_parent_notebook_section_groups = UsersOnenotePagesParentNotebookSectionGroupsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.users_onenote_pages_parent_notebook_section_groups_sections = UsersOnenotePagesParentNotebookSectionGroupsSectionsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.users_onenote_pages_parent_notebook_sections = UsersOnenotePagesParentNotebookSectionsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.users_onenote_pages_parent_notebook_sections_parent_section_group = UsersOnenotePagesParentNotebookSectionsParentSectionGroupOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.users_onenote_pages_parent_section = UsersOnenotePagesParentSectionOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.users_onenote_pages_parent_section_parent_notebook = UsersOnenotePagesParentSectionParentNotebookOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.users_onenote_pages_parent_section_parent_notebook_section_groups = UsersOnenotePagesParentSectionParentNotebookSectionGroupsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.users_onenote_pages_parent_section_parent_section_group = UsersOnenotePagesParentSectionParentSectionGroupOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.users_onenote_pages_parent_section_parent_section_group_parent_notebook = UsersOnenotePagesParentSectionParentSectionGroupParentNotebookOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.users_onenote_section_groups = UsersOnenoteSectionGroupsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.users_onenote_section_groups_parent_notebook = UsersOnenoteSectionGroupsParentNotebookOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.users_onenote_section_groups_parent_notebook_sections = UsersOnenoteSectionGroupsParentNotebookSectionsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.users_onenote_section_groups_parent_notebook_sections_pages = UsersOnenoteSectionGroupsParentNotebookSectionsPagesOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.users_onenote_section_groups_sections = UsersOnenoteSectionGroupsSectionsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.users_onenote_section_groups_sections_pages = UsersOnenoteSectionGroupsSectionsPagesOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.users_onenote_section_groups_sections_pages_parent_notebook = UsersOnenoteSectionGroupsSectionsPagesParentNotebookOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.users_onenote_section_groups_sections_parent_notebook = UsersOnenoteSectionGroupsSectionsParentNotebookOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.users_onenote_sections = UsersOnenoteSectionsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.users_onenote_sections_pages = UsersOnenoteSectionsPagesOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.users_onenote_sections_pages_parent_notebook = UsersOnenoteSectionsPagesParentNotebookOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.users_onenote_sections_pages_parent_notebook_section_groups = UsersOnenoteSectionsPagesParentNotebookSectionGroupsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.users_onenote_sections_parent_notebook = UsersOnenoteSectionsParentNotebookOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.users_onenote_sections_parent_notebook_section_groups = UsersOnenoteSectionsParentNotebookSectionGroupsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.users_onenote_sections_parent_section_group = UsersOnenoteSectionsParentSectionGroupOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.users_onenote_sections_parent_section_group_parent_notebook = UsersOnenoteSectionsParentSectionGroupParentNotebookOperations(
            self._client, self._config, self._serialize, self._deserialize)

    async def close(self) -> None:
        await self._client.close()

    async def __aenter__(self) -> "Notes":
        await self._client.__aenter__()
        return self

    async def __aexit__(self, *exc_details) -> None:
        await self._client.__aexit__(*exc_details)
