installed_extensions = [ 'azext_applications',
 'azext_changenotifications',
 'azext_cloudcommunications',
 'azext_crossdeviceexperiences',
 'azext_devicescorporatemanagement',
 'azext_directoryobjects',
 'azext_mail',
 'azext_notes',
 'azext_people',
 'azext_personalcontacts',
 'azext_reports',
 'azext_schemaextensions',
 'azext_users',
]