# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------
import datetime
from typing import Any, Callable, Dict, Generic, List, Optional, TypeVar, Union
import warnings

from azure.core.exceptions import ClientAuthenticationError, HttpResponseError, ResourceExistsError, ResourceNotFoundError, map_error
from azure.core.pipeline import PipelineResponse
from azure.core.pipeline.transport import AsyncHttpResponse, HttpRequest
from azure.mgmt.core.exceptions import ARMErrorFormat

from ... import models

T = TypeVar('T')
ClsType = Optional[Callable[[PipelineResponse[HttpRequest, AsyncHttpResponse], T, Dict[str, Any]], Any]]

class UserMailFolderMessageOperations:
    """UserMailFolderMessageOperations async operations.

    You should not instantiate this class directly. Instead, you should create a Client instance that
    instantiates it for you and attaches it as an attribute.

    :ivar models: Alias to model classes used in this operation group.
    :type models: ~users_actions.models
    :param client: Client for service requests.
    :param config: Configuration of service client.
    :param serializer: An object model serializer.
    :param deserializer: An object model deserializer.
    """

    models = models

    def __init__(self, client, config, serializer, deserializer) -> None:
        self._client = client
        self._serialize = serializer
        self._deserialize = deserializer
        self._config = config

    async def copy(
        self,
        user_id: str,
        mail_folder_id: str,
        message_id: str,
        destination_id: Optional[str] = None,
        **kwargs
    ) -> "models.MicrosoftGraphMessage":
        """Invoke action copy.

        Invoke action copy.

        :param user_id: key: id of user.
        :type user_id: str
        :param mail_folder_id: key: id of mailFolder.
        :type mail_folder_id: str
        :param message_id: key: id of message.
        :type message_id: str
        :param destination_id:
        :type destination_id: str
        :keyword callable cls: A custom type or function that will be passed the direct response
        :return: MicrosoftGraphMessage, or the result of cls(response)
        :rtype: ~users_actions.models.MicrosoftGraphMessage
        :raises: ~azure.core.exceptions.HttpResponseError
        """
        cls = kwargs.pop('cls', None)  # type: ClsType["models.MicrosoftGraphMessage"]
        error_map = {
            401: ClientAuthenticationError, 404: ResourceNotFoundError, 409: ResourceExistsError
        }
        error_map.update(kwargs.pop('error_map', {}))

        body = models.PathsDy94GcUsersUserIdMailfoldersMailfolderIdMessagesMessageIdMicrosoftGraphCopyPostRequestbodyContentApplicationJsonSchema(destination_id=destination_id)
        content_type = kwargs.pop("content_type", "application/json")
        accept = "application/json"

        # Construct URL
        url = self.copy.metadata['url']  # type: ignore
        path_format_arguments = {
            'user-id': self._serialize.url("user_id", user_id, 'str'),
            'mailFolder-id': self._serialize.url("mail_folder_id", mail_folder_id, 'str'),
            'message-id': self._serialize.url("message_id", message_id, 'str'),
        }
        url = self._client.format_url(url, **path_format_arguments)

        # Construct parameters
        query_parameters = {}  # type: Dict[str, Any]

        # Construct headers
        header_parameters = {}  # type: Dict[str, Any]
        header_parameters['Content-Type'] = self._serialize.header("content_type", content_type, 'str')
        header_parameters['Accept'] = self._serialize.header("accept", accept, 'str')

        body_content_kwargs = {}  # type: Dict[str, Any]
        body_content = self._serialize.body(body, 'PathsDy94GcUsersUserIdMailfoldersMailfolderIdMessagesMessageIdMicrosoftGraphCopyPostRequestbodyContentApplicationJsonSchema')
        body_content_kwargs['content'] = body_content
        request = self._client.post(url, query_parameters, header_parameters, **body_content_kwargs)
        pipeline_response = await self._client._pipeline.run(request, stream=False, **kwargs)
        response = pipeline_response.http_response

        if response.status_code not in [200]:
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            error = self._deserialize(models.OdataError, response)
            raise HttpResponseError(response=response, model=error, error_format=ARMErrorFormat)

        deserialized = self._deserialize('MicrosoftGraphMessage', pipeline_response)

        if cls:
            return cls(pipeline_response, deserialized, {})

        return deserialized
    copy.metadata = {'url': '/users/{user-id}/mailFolders/{mailFolder-id}/messages/{message-id}/microsoft.graph.copy'}  # type: ignore

    async def create_forward(
        self,
        user_id: str,
        mail_folder_id: str,
        message_id: str,
        to_recipients: Optional[List["models.MicrosoftGraphRecipient"]] = None,
        comment: Optional[str] = None,
        id: Optional[str] = None,
        categories: Optional[List[str]] = None,
        change_key: Optional[str] = None,
        created_date_time: Optional[datetime.datetime] = None,
        last_modified_date_time: Optional[datetime.datetime] = None,
        bcc_recipients: Optional[List["models.MicrosoftGraphRecipient"]] = None,
        body: Optional["models.MicrosoftGraphItemBody"] = None,
        body_preview: Optional[str] = None,
        cc_recipients: Optional[List["models.MicrosoftGraphRecipient"]] = None,
        conversation_id: Optional[str] = None,
        conversation_index: Optional[bytes] = None,
        flag: Optional["models.MicrosoftGraphFollowupFlag"] = None,
        from_parameter: Optional["models.MicrosoftGraphRecipient"] = None,
        has_attachments: Optional[bool] = None,
        importance: Optional[Union[str, "models.MicrosoftGraphImportance"]] = None,
        inference_classification: Optional[Union[str, "models.MicrosoftGraphInferenceClassificationType"]] = None,
        internet_message_headers: Optional[List["models.MicrosoftGraphInternetMessageHeader"]] = None,
        internet_message_id: Optional[str] = None,
        is_delivery_receipt_requested: Optional[bool] = None,
        is_draft: Optional[bool] = None,
        is_read: Optional[bool] = None,
        is_read_receipt_requested: Optional[bool] = None,
        parent_folder_id: Optional[str] = None,
        received_date_time: Optional[datetime.datetime] = None,
        reply_to: Optional[List["models.MicrosoftGraphRecipient"]] = None,
        sender: Optional["models.MicrosoftGraphRecipient"] = None,
        sent_date_time: Optional[datetime.datetime] = None,
        subject: Optional[str] = None,
        microsoft_graph_message_to_recipients: Optional[List["models.MicrosoftGraphRecipient"]] = None,
        unique_body: Optional["models.MicrosoftGraphItemBody"] = None,
        web_link: Optional[str] = None,
        attachments: Optional[List["models.MicrosoftGraphAttachment"]] = None,
        extensions: Optional[List["models.MicrosoftGraphExtension"]] = None,
        multi_value_extended_properties: Optional[List["models.MicrosoftGraphMultiValueLegacyExtendedProperty"]] = None,
        single_value_extended_properties: Optional[List["models.MicrosoftGraphSingleValueLegacyExtendedProperty"]] = None,
        **kwargs
    ) -> "models.MicrosoftGraphMessage":
        """Invoke action createForward.

        Invoke action createForward.

        :param user_id: key: id of user.
        :type user_id: str
        :param mail_folder_id: key: id of mailFolder.
        :type mail_folder_id: str
        :param message_id: key: id of message.
        :type message_id: str
        :param to_recipients:
        :type to_recipients: list[~users_actions.models.MicrosoftGraphRecipient]
        :param comment:
        :type comment: str
        :param id: Read-only.
        :type id: str
        :param categories: The categories associated with the item.
        :type categories: list[str]
        :param change_key: Identifies the version of the item. Every time the item is changed,
         changeKey changes as well. This allows Exchange to apply changes to the correct version of the
         object. Read-only.
        :type change_key: str
        :param created_date_time: The Timestamp type represents date and time information using ISO
         8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 would look like
         this: '2014-01-01T00:00:00Z'.
        :type created_date_time: ~datetime.datetime
        :param last_modified_date_time: The Timestamp type represents date and time information using
         ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 would look
         like this: '2014-01-01T00:00:00Z'.
        :type last_modified_date_time: ~datetime.datetime
        :param bcc_recipients: The Bcc: recipients for the message.
        :type bcc_recipients: list[~users_actions.models.MicrosoftGraphRecipient]
        :param body: itemBody.
        :type body: ~users_actions.models.MicrosoftGraphItemBody
        :param body_preview: The first 255 characters of the message body. It is in text format.
        :type body_preview: str
        :param cc_recipients: The Cc: recipients for the message.
        :type cc_recipients: list[~users_actions.models.MicrosoftGraphRecipient]
        :param conversation_id: The ID of the conversation the email belongs to.
        :type conversation_id: str
        :param conversation_index: Indicates the position of the message within the conversation.
        :type conversation_index: bytes
        :param flag: followupFlag.
        :type flag: ~users_actions.models.MicrosoftGraphFollowupFlag
        :param from_parameter: recipient.
        :type from_parameter: ~users_actions.models.MicrosoftGraphRecipient
        :param has_attachments: Indicates whether the message has attachments. This property doesn't
         include inline attachments, so if a message contains only inline attachments, this property is
         false. To verify the existence of inline attachments, parse the body property to look for a src
         attribute, such as :code:`<IMG src='cid:image001.jpg@01D26CD8.6C05F070'>`.
        :type has_attachments: bool
        :param importance:
        :type importance: str or ~users_actions.models.MicrosoftGraphImportance
        :param inference_classification:
        :type inference_classification: str or ~users_actions.models.MicrosoftGraphInferenceClassificationType
        :param internet_message_headers: A collection of message headers defined by RFC5322. The set
         includes message headers indicating the network path taken by a message from the sender to the
         recipient. It can also contain custom message headers that hold app data for the message.
         Returned only on applying a $select query option. Read-only.
        :type internet_message_headers: list[~users_actions.models.MicrosoftGraphInternetMessageHeader]
        :param internet_message_id: The message ID in the format specified by RFC2822.
        :type internet_message_id: str
        :param is_delivery_receipt_requested: Indicates whether a read receipt is requested for the
         message.
        :type is_delivery_receipt_requested: bool
        :param is_draft: Indicates whether the message is a draft. A message is a draft if it hasn't
         been sent yet.
        :type is_draft: bool
        :param is_read: Indicates whether the message has been read.
        :type is_read: bool
        :param is_read_receipt_requested: Indicates whether a read receipt is requested for the
         message.
        :type is_read_receipt_requested: bool
        :param parent_folder_id: The unique identifier for the message's parent mailFolder.
        :type parent_folder_id: str
        :param received_date_time: The date and time the message was received.
        :type received_date_time: ~datetime.datetime
        :param reply_to: The email addresses to use when replying.
        :type reply_to: list[~users_actions.models.MicrosoftGraphRecipient]
        :param sender: recipient.
        :type sender: ~users_actions.models.MicrosoftGraphRecipient
        :param sent_date_time: The date and time the message was sent.
        :type sent_date_time: ~datetime.datetime
        :param subject: The subject of the message.
        :type subject: str
        :param microsoft_graph_message_to_recipients: The To: recipients for the message.
        :type microsoft_graph_message_to_recipients: list[~users_actions.models.MicrosoftGraphRecipient]
        :param unique_body: itemBody.
        :type unique_body: ~users_actions.models.MicrosoftGraphItemBody
        :param web_link: The URL to open the message in Outlook Web App.You can append an ispopout
         argument to the end of the URL to change how the message is displayed. If ispopout is not
         present or if it is set to 1, then the message is shown in a popout window. If ispopout is set
         to 0, then the browser will show the message in the Outlook Web App review pane.The message
         will open in the browser if you are logged in to your mailbox via Outlook Web App. You will be
         prompted to login if you are not already logged in with the browser.This URL can be accessed
         from within an iFrame.
        :type web_link: str
        :param attachments: The fileAttachment and itemAttachment attachments for the message.
        :type attachments: list[~users_actions.models.MicrosoftGraphAttachment]
        :param extensions: The collection of open extensions defined for the message. Nullable.
        :type extensions: list[~users_actions.models.MicrosoftGraphExtension]
        :param multi_value_extended_properties: The collection of multi-value extended properties
         defined for the message. Nullable.
        :type multi_value_extended_properties: list[~users_actions.models.MicrosoftGraphMultiValueLegacyExtendedProperty]
        :param single_value_extended_properties: The collection of single-value extended properties
         defined for the message. Nullable.
        :type single_value_extended_properties: list[~users_actions.models.MicrosoftGraphSingleValueLegacyExtendedProperty]
        :keyword callable cls: A custom type or function that will be passed the direct response
        :return: MicrosoftGraphMessage, or the result of cls(response)
        :rtype: ~users_actions.models.MicrosoftGraphMessage
        :raises: ~azure.core.exceptions.HttpResponseError
        """
        cls = kwargs.pop('cls', None)  # type: ClsType["models.MicrosoftGraphMessage"]
        error_map = {
            401: ClientAuthenticationError, 404: ResourceNotFoundError, 409: ResourceExistsError
        }
        error_map.update(kwargs.pop('error_map', {}))

        body = models.Paths29L6IuUsersUserIdMailfoldersMailfolderIdMessagesMessageIdMicrosoftGraphCreateforwardPostRequestbodyContentApplicationJsonSchema(to_recipients=to_recipients, comment=comment, id=id, categories=categories, change_key=change_key, created_date_time=created_date_time, last_modified_date_time=last_modified_date_time, bcc_recipients=bcc_recipients, body=body, body_preview=body_preview, cc_recipients=cc_recipients, conversation_id=conversation_id, conversation_index=conversation_index, flag=flag, from_property=from_parameter, has_attachments=has_attachments, importance=importance, inference_classification=inference_classification, internet_message_headers=internet_message_headers, internet_message_id=internet_message_id, is_delivery_receipt_requested=is_delivery_receipt_requested, is_draft=is_draft, is_read=is_read, is_read_receipt_requested=is_read_receipt_requested, parent_folder_id=parent_folder_id, received_date_time=received_date_time, reply_to=reply_to, sender=sender, sent_date_time=sent_date_time, subject=subject, to_recipients_message_to_recipients=microsoft_graph_message_to_recipients, unique_body=unique_body, web_link=web_link, attachments=attachments, extensions=extensions, multi_value_extended_properties=multi_value_extended_properties, single_value_extended_properties=single_value_extended_properties)
        content_type = kwargs.pop("content_type", "application/json")
        accept = "application/json"

        # Construct URL
        url = self.create_forward.metadata['url']  # type: ignore
        path_format_arguments = {
            'user-id': self._serialize.url("user_id", user_id, 'str'),
            'mailFolder-id': self._serialize.url("mail_folder_id", mail_folder_id, 'str'),
            'message-id': self._serialize.url("message_id", message_id, 'str'),
        }
        url = self._client.format_url(url, **path_format_arguments)

        # Construct parameters
        query_parameters = {}  # type: Dict[str, Any]

        # Construct headers
        header_parameters = {}  # type: Dict[str, Any]
        header_parameters['Content-Type'] = self._serialize.header("content_type", content_type, 'str')
        header_parameters['Accept'] = self._serialize.header("accept", accept, 'str')

        body_content_kwargs = {}  # type: Dict[str, Any]
        body_content = self._serialize.body(body, 'Paths29L6IuUsersUserIdMailfoldersMailfolderIdMessagesMessageIdMicrosoftGraphCreateforwardPostRequestbodyContentApplicationJsonSchema')
        body_content_kwargs['content'] = body_content
        request = self._client.post(url, query_parameters, header_parameters, **body_content_kwargs)
        pipeline_response = await self._client._pipeline.run(request, stream=False, **kwargs)
        response = pipeline_response.http_response

        if response.status_code not in [200]:
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            error = self._deserialize(models.OdataError, response)
            raise HttpResponseError(response=response, model=error, error_format=ARMErrorFormat)

        deserialized = self._deserialize('MicrosoftGraphMessage', pipeline_response)

        if cls:
            return cls(pipeline_response, deserialized, {})

        return deserialized
    create_forward.metadata = {'url': '/users/{user-id}/mailFolders/{mailFolder-id}/messages/{message-id}/microsoft.graph.createForward'}  # type: ignore

    async def create_reply(
        self,
        user_id: str,
        mail_folder_id: str,
        message_id: str,
        comment: Optional[str] = None,
        id: Optional[str] = None,
        categories: Optional[List[str]] = None,
        change_key: Optional[str] = None,
        created_date_time: Optional[datetime.datetime] = None,
        last_modified_date_time: Optional[datetime.datetime] = None,
        bcc_recipients: Optional[List["models.MicrosoftGraphRecipient"]] = None,
        body: Optional["models.MicrosoftGraphItemBody"] = None,
        body_preview: Optional[str] = None,
        cc_recipients: Optional[List["models.MicrosoftGraphRecipient"]] = None,
        conversation_id: Optional[str] = None,
        conversation_index: Optional[bytes] = None,
        flag: Optional["models.MicrosoftGraphFollowupFlag"] = None,
        from_parameter: Optional["models.MicrosoftGraphRecipient"] = None,
        has_attachments: Optional[bool] = None,
        importance: Optional[Union[str, "models.MicrosoftGraphImportance"]] = None,
        inference_classification: Optional[Union[str, "models.MicrosoftGraphInferenceClassificationType"]] = None,
        internet_message_headers: Optional[List["models.MicrosoftGraphInternetMessageHeader"]] = None,
        internet_message_id: Optional[str] = None,
        is_delivery_receipt_requested: Optional[bool] = None,
        is_draft: Optional[bool] = None,
        is_read: Optional[bool] = None,
        is_read_receipt_requested: Optional[bool] = None,
        parent_folder_id: Optional[str] = None,
        received_date_time: Optional[datetime.datetime] = None,
        reply_to: Optional[List["models.MicrosoftGraphRecipient"]] = None,
        sender: Optional["models.MicrosoftGraphRecipient"] = None,
        sent_date_time: Optional[datetime.datetime] = None,
        subject: Optional[str] = None,
        to_recipients: Optional[List["models.MicrosoftGraphRecipient"]] = None,
        unique_body: Optional["models.MicrosoftGraphItemBody"] = None,
        web_link: Optional[str] = None,
        attachments: Optional[List["models.MicrosoftGraphAttachment"]] = None,
        extensions: Optional[List["models.MicrosoftGraphExtension"]] = None,
        multi_value_extended_properties: Optional[List["models.MicrosoftGraphMultiValueLegacyExtendedProperty"]] = None,
        single_value_extended_properties: Optional[List["models.MicrosoftGraphSingleValueLegacyExtendedProperty"]] = None,
        **kwargs
    ) -> "models.MicrosoftGraphMessage":
        """Invoke action createReply.

        Invoke action createReply.

        :param user_id: key: id of user.
        :type user_id: str
        :param mail_folder_id: key: id of mailFolder.
        :type mail_folder_id: str
        :param message_id: key: id of message.
        :type message_id: str
        :param comment:
        :type comment: str
        :param id: Read-only.
        :type id: str
        :param categories: The categories associated with the item.
        :type categories: list[str]
        :param change_key: Identifies the version of the item. Every time the item is changed,
         changeKey changes as well. This allows Exchange to apply changes to the correct version of the
         object. Read-only.
        :type change_key: str
        :param created_date_time: The Timestamp type represents date and time information using ISO
         8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 would look like
         this: '2014-01-01T00:00:00Z'.
        :type created_date_time: ~datetime.datetime
        :param last_modified_date_time: The Timestamp type represents date and time information using
         ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 would look
         like this: '2014-01-01T00:00:00Z'.
        :type last_modified_date_time: ~datetime.datetime
        :param bcc_recipients: The Bcc: recipients for the message.
        :type bcc_recipients: list[~users_actions.models.MicrosoftGraphRecipient]
        :param body: itemBody.
        :type body: ~users_actions.models.MicrosoftGraphItemBody
        :param body_preview: The first 255 characters of the message body. It is in text format.
        :type body_preview: str
        :param cc_recipients: The Cc: recipients for the message.
        :type cc_recipients: list[~users_actions.models.MicrosoftGraphRecipient]
        :param conversation_id: The ID of the conversation the email belongs to.
        :type conversation_id: str
        :param conversation_index: Indicates the position of the message within the conversation.
        :type conversation_index: bytes
        :param flag: followupFlag.
        :type flag: ~users_actions.models.MicrosoftGraphFollowupFlag
        :param from_parameter: recipient.
        :type from_parameter: ~users_actions.models.MicrosoftGraphRecipient
        :param has_attachments: Indicates whether the message has attachments. This property doesn't
         include inline attachments, so if a message contains only inline attachments, this property is
         false. To verify the existence of inline attachments, parse the body property to look for a src
         attribute, such as :code:`<IMG src='cid:image001.jpg@01D26CD8.6C05F070'>`.
        :type has_attachments: bool
        :param importance:
        :type importance: str or ~users_actions.models.MicrosoftGraphImportance
        :param inference_classification:
        :type inference_classification: str or ~users_actions.models.MicrosoftGraphInferenceClassificationType
        :param internet_message_headers: A collection of message headers defined by RFC5322. The set
         includes message headers indicating the network path taken by a message from the sender to the
         recipient. It can also contain custom message headers that hold app data for the message.
         Returned only on applying a $select query option. Read-only.
        :type internet_message_headers: list[~users_actions.models.MicrosoftGraphInternetMessageHeader]
        :param internet_message_id: The message ID in the format specified by RFC2822.
        :type internet_message_id: str
        :param is_delivery_receipt_requested: Indicates whether a read receipt is requested for the
         message.
        :type is_delivery_receipt_requested: bool
        :param is_draft: Indicates whether the message is a draft. A message is a draft if it hasn't
         been sent yet.
        :type is_draft: bool
        :param is_read: Indicates whether the message has been read.
        :type is_read: bool
        :param is_read_receipt_requested: Indicates whether a read receipt is requested for the
         message.
        :type is_read_receipt_requested: bool
        :param parent_folder_id: The unique identifier for the message's parent mailFolder.
        :type parent_folder_id: str
        :param received_date_time: The date and time the message was received.
        :type received_date_time: ~datetime.datetime
        :param reply_to: The email addresses to use when replying.
        :type reply_to: list[~users_actions.models.MicrosoftGraphRecipient]
        :param sender: recipient.
        :type sender: ~users_actions.models.MicrosoftGraphRecipient
        :param sent_date_time: The date and time the message was sent.
        :type sent_date_time: ~datetime.datetime
        :param subject: The subject of the message.
        :type subject: str
        :param to_recipients: The To: recipients for the message.
        :type to_recipients: list[~users_actions.models.MicrosoftGraphRecipient]
        :param unique_body: itemBody.
        :type unique_body: ~users_actions.models.MicrosoftGraphItemBody
        :param web_link: The URL to open the message in Outlook Web App.You can append an ispopout
         argument to the end of the URL to change how the message is displayed. If ispopout is not
         present or if it is set to 1, then the message is shown in a popout window. If ispopout is set
         to 0, then the browser will show the message in the Outlook Web App review pane.The message
         will open in the browser if you are logged in to your mailbox via Outlook Web App. You will be
         prompted to login if you are not already logged in with the browser.This URL can be accessed
         from within an iFrame.
        :type web_link: str
        :param attachments: The fileAttachment and itemAttachment attachments for the message.
        :type attachments: list[~users_actions.models.MicrosoftGraphAttachment]
        :param extensions: The collection of open extensions defined for the message. Nullable.
        :type extensions: list[~users_actions.models.MicrosoftGraphExtension]
        :param multi_value_extended_properties: The collection of multi-value extended properties
         defined for the message. Nullable.
        :type multi_value_extended_properties: list[~users_actions.models.MicrosoftGraphMultiValueLegacyExtendedProperty]
        :param single_value_extended_properties: The collection of single-value extended properties
         defined for the message. Nullable.
        :type single_value_extended_properties: list[~users_actions.models.MicrosoftGraphSingleValueLegacyExtendedProperty]
        :keyword callable cls: A custom type or function that will be passed the direct response
        :return: MicrosoftGraphMessage, or the result of cls(response)
        :rtype: ~users_actions.models.MicrosoftGraphMessage
        :raises: ~azure.core.exceptions.HttpResponseError
        """
        cls = kwargs.pop('cls', None)  # type: ClsType["models.MicrosoftGraphMessage"]
        error_map = {
            401: ClientAuthenticationError, 404: ResourceNotFoundError, 409: ResourceExistsError
        }
        error_map.update(kwargs.pop('error_map', {}))

        body = models.PathsGpd5XxUsersUserIdMailfoldersMailfolderIdMessagesMessageIdMicrosoftGraphCreatereplyPostRequestbodyContentApplicationJsonSchema(comment=comment, id=id, categories=categories, change_key=change_key, created_date_time=created_date_time, last_modified_date_time=last_modified_date_time, bcc_recipients=bcc_recipients, body=body, body_preview=body_preview, cc_recipients=cc_recipients, conversation_id=conversation_id, conversation_index=conversation_index, flag=flag, from_property=from_parameter, has_attachments=has_attachments, importance=importance, inference_classification=inference_classification, internet_message_headers=internet_message_headers, internet_message_id=internet_message_id, is_delivery_receipt_requested=is_delivery_receipt_requested, is_draft=is_draft, is_read=is_read, is_read_receipt_requested=is_read_receipt_requested, parent_folder_id=parent_folder_id, received_date_time=received_date_time, reply_to=reply_to, sender=sender, sent_date_time=sent_date_time, subject=subject, to_recipients=to_recipients, unique_body=unique_body, web_link=web_link, attachments=attachments, extensions=extensions, multi_value_extended_properties=multi_value_extended_properties, single_value_extended_properties=single_value_extended_properties)
        content_type = kwargs.pop("content_type", "application/json")
        accept = "application/json"

        # Construct URL
        url = self.create_reply.metadata['url']  # type: ignore
        path_format_arguments = {
            'user-id': self._serialize.url("user_id", user_id, 'str'),
            'mailFolder-id': self._serialize.url("mail_folder_id", mail_folder_id, 'str'),
            'message-id': self._serialize.url("message_id", message_id, 'str'),
        }
        url = self._client.format_url(url, **path_format_arguments)

        # Construct parameters
        query_parameters = {}  # type: Dict[str, Any]

        # Construct headers
        header_parameters = {}  # type: Dict[str, Any]
        header_parameters['Content-Type'] = self._serialize.header("content_type", content_type, 'str')
        header_parameters['Accept'] = self._serialize.header("accept", accept, 'str')

        body_content_kwargs = {}  # type: Dict[str, Any]
        body_content = self._serialize.body(body, 'PathsGpd5XxUsersUserIdMailfoldersMailfolderIdMessagesMessageIdMicrosoftGraphCreatereplyPostRequestbodyContentApplicationJsonSchema')
        body_content_kwargs['content'] = body_content
        request = self._client.post(url, query_parameters, header_parameters, **body_content_kwargs)
        pipeline_response = await self._client._pipeline.run(request, stream=False, **kwargs)
        response = pipeline_response.http_response

        if response.status_code not in [200]:
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            error = self._deserialize(models.OdataError, response)
            raise HttpResponseError(response=response, model=error, error_format=ARMErrorFormat)

        deserialized = self._deserialize('MicrosoftGraphMessage', pipeline_response)

        if cls:
            return cls(pipeline_response, deserialized, {})

        return deserialized
    create_reply.metadata = {'url': '/users/{user-id}/mailFolders/{mailFolder-id}/messages/{message-id}/microsoft.graph.createReply'}  # type: ignore

    async def create_reply_all(
        self,
        user_id: str,
        mail_folder_id: str,
        message_id: str,
        comment: Optional[str] = None,
        id: Optional[str] = None,
        categories: Optional[List[str]] = None,
        change_key: Optional[str] = None,
        created_date_time: Optional[datetime.datetime] = None,
        last_modified_date_time: Optional[datetime.datetime] = None,
        bcc_recipients: Optional[List["models.MicrosoftGraphRecipient"]] = None,
        body: Optional["models.MicrosoftGraphItemBody"] = None,
        body_preview: Optional[str] = None,
        cc_recipients: Optional[List["models.MicrosoftGraphRecipient"]] = None,
        conversation_id: Optional[str] = None,
        conversation_index: Optional[bytes] = None,
        flag: Optional["models.MicrosoftGraphFollowupFlag"] = None,
        from_parameter: Optional["models.MicrosoftGraphRecipient"] = None,
        has_attachments: Optional[bool] = None,
        importance: Optional[Union[str, "models.MicrosoftGraphImportance"]] = None,
        inference_classification: Optional[Union[str, "models.MicrosoftGraphInferenceClassificationType"]] = None,
        internet_message_headers: Optional[List["models.MicrosoftGraphInternetMessageHeader"]] = None,
        internet_message_id: Optional[str] = None,
        is_delivery_receipt_requested: Optional[bool] = None,
        is_draft: Optional[bool] = None,
        is_read: Optional[bool] = None,
        is_read_receipt_requested: Optional[bool] = None,
        parent_folder_id: Optional[str] = None,
        received_date_time: Optional[datetime.datetime] = None,
        reply_to: Optional[List["models.MicrosoftGraphRecipient"]] = None,
        sender: Optional["models.MicrosoftGraphRecipient"] = None,
        sent_date_time: Optional[datetime.datetime] = None,
        subject: Optional[str] = None,
        to_recipients: Optional[List["models.MicrosoftGraphRecipient"]] = None,
        unique_body: Optional["models.MicrosoftGraphItemBody"] = None,
        web_link: Optional[str] = None,
        attachments: Optional[List["models.MicrosoftGraphAttachment"]] = None,
        extensions: Optional[List["models.MicrosoftGraphExtension"]] = None,
        multi_value_extended_properties: Optional[List["models.MicrosoftGraphMultiValueLegacyExtendedProperty"]] = None,
        single_value_extended_properties: Optional[List["models.MicrosoftGraphSingleValueLegacyExtendedProperty"]] = None,
        **kwargs
    ) -> "models.MicrosoftGraphMessage":
        """Invoke action createReplyAll.

        Invoke action createReplyAll.

        :param user_id: key: id of user.
        :type user_id: str
        :param mail_folder_id: key: id of mailFolder.
        :type mail_folder_id: str
        :param message_id: key: id of message.
        :type message_id: str
        :param comment:
        :type comment: str
        :param id: Read-only.
        :type id: str
        :param categories: The categories associated with the item.
        :type categories: list[str]
        :param change_key: Identifies the version of the item. Every time the item is changed,
         changeKey changes as well. This allows Exchange to apply changes to the correct version of the
         object. Read-only.
        :type change_key: str
        :param created_date_time: The Timestamp type represents date and time information using ISO
         8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 would look like
         this: '2014-01-01T00:00:00Z'.
        :type created_date_time: ~datetime.datetime
        :param last_modified_date_time: The Timestamp type represents date and time information using
         ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 would look
         like this: '2014-01-01T00:00:00Z'.
        :type last_modified_date_time: ~datetime.datetime
        :param bcc_recipients: The Bcc: recipients for the message.
        :type bcc_recipients: list[~users_actions.models.MicrosoftGraphRecipient]
        :param body: itemBody.
        :type body: ~users_actions.models.MicrosoftGraphItemBody
        :param body_preview: The first 255 characters of the message body. It is in text format.
        :type body_preview: str
        :param cc_recipients: The Cc: recipients for the message.
        :type cc_recipients: list[~users_actions.models.MicrosoftGraphRecipient]
        :param conversation_id: The ID of the conversation the email belongs to.
        :type conversation_id: str
        :param conversation_index: Indicates the position of the message within the conversation.
        :type conversation_index: bytes
        :param flag: followupFlag.
        :type flag: ~users_actions.models.MicrosoftGraphFollowupFlag
        :param from_parameter: recipient.
        :type from_parameter: ~users_actions.models.MicrosoftGraphRecipient
        :param has_attachments: Indicates whether the message has attachments. This property doesn't
         include inline attachments, so if a message contains only inline attachments, this property is
         false. To verify the existence of inline attachments, parse the body property to look for a src
         attribute, such as :code:`<IMG src='cid:image001.jpg@01D26CD8.6C05F070'>`.
        :type has_attachments: bool
        :param importance:
        :type importance: str or ~users_actions.models.MicrosoftGraphImportance
        :param inference_classification:
        :type inference_classification: str or ~users_actions.models.MicrosoftGraphInferenceClassificationType
        :param internet_message_headers: A collection of message headers defined by RFC5322. The set
         includes message headers indicating the network path taken by a message from the sender to the
         recipient. It can also contain custom message headers that hold app data for the message.
         Returned only on applying a $select query option. Read-only.
        :type internet_message_headers: list[~users_actions.models.MicrosoftGraphInternetMessageHeader]
        :param internet_message_id: The message ID in the format specified by RFC2822.
        :type internet_message_id: str
        :param is_delivery_receipt_requested: Indicates whether a read receipt is requested for the
         message.
        :type is_delivery_receipt_requested: bool
        :param is_draft: Indicates whether the message is a draft. A message is a draft if it hasn't
         been sent yet.
        :type is_draft: bool
        :param is_read: Indicates whether the message has been read.
        :type is_read: bool
        :param is_read_receipt_requested: Indicates whether a read receipt is requested for the
         message.
        :type is_read_receipt_requested: bool
        :param parent_folder_id: The unique identifier for the message's parent mailFolder.
        :type parent_folder_id: str
        :param received_date_time: The date and time the message was received.
        :type received_date_time: ~datetime.datetime
        :param reply_to: The email addresses to use when replying.
        :type reply_to: list[~users_actions.models.MicrosoftGraphRecipient]
        :param sender: recipient.
        :type sender: ~users_actions.models.MicrosoftGraphRecipient
        :param sent_date_time: The date and time the message was sent.
        :type sent_date_time: ~datetime.datetime
        :param subject: The subject of the message.
        :type subject: str
        :param to_recipients: The To: recipients for the message.
        :type to_recipients: list[~users_actions.models.MicrosoftGraphRecipient]
        :param unique_body: itemBody.
        :type unique_body: ~users_actions.models.MicrosoftGraphItemBody
        :param web_link: The URL to open the message in Outlook Web App.You can append an ispopout
         argument to the end of the URL to change how the message is displayed. If ispopout is not
         present or if it is set to 1, then the message is shown in a popout window. If ispopout is set
         to 0, then the browser will show the message in the Outlook Web App review pane.The message
         will open in the browser if you are logged in to your mailbox via Outlook Web App. You will be
         prompted to login if you are not already logged in with the browser.This URL can be accessed
         from within an iFrame.
        :type web_link: str
        :param attachments: The fileAttachment and itemAttachment attachments for the message.
        :type attachments: list[~users_actions.models.MicrosoftGraphAttachment]
        :param extensions: The collection of open extensions defined for the message. Nullable.
        :type extensions: list[~users_actions.models.MicrosoftGraphExtension]
        :param multi_value_extended_properties: The collection of multi-value extended properties
         defined for the message. Nullable.
        :type multi_value_extended_properties: list[~users_actions.models.MicrosoftGraphMultiValueLegacyExtendedProperty]
        :param single_value_extended_properties: The collection of single-value extended properties
         defined for the message. Nullable.
        :type single_value_extended_properties: list[~users_actions.models.MicrosoftGraphSingleValueLegacyExtendedProperty]
        :keyword callable cls: A custom type or function that will be passed the direct response
        :return: MicrosoftGraphMessage, or the result of cls(response)
        :rtype: ~users_actions.models.MicrosoftGraphMessage
        :raises: ~azure.core.exceptions.HttpResponseError
        """
        cls = kwargs.pop('cls', None)  # type: ClsType["models.MicrosoftGraphMessage"]
        error_map = {
            401: ClientAuthenticationError, 404: ResourceNotFoundError, 409: ResourceExistsError
        }
        error_map.update(kwargs.pop('error_map', {}))

        body = models.Paths3M6QbmUsersUserIdMailfoldersMailfolderIdMessagesMessageIdMicrosoftGraphCreatereplyallPostRequestbodyContentApplicationJsonSchema(comment=comment, id=id, categories=categories, change_key=change_key, created_date_time=created_date_time, last_modified_date_time=last_modified_date_time, bcc_recipients=bcc_recipients, body=body, body_preview=body_preview, cc_recipients=cc_recipients, conversation_id=conversation_id, conversation_index=conversation_index, flag=flag, from_property=from_parameter, has_attachments=has_attachments, importance=importance, inference_classification=inference_classification, internet_message_headers=internet_message_headers, internet_message_id=internet_message_id, is_delivery_receipt_requested=is_delivery_receipt_requested, is_draft=is_draft, is_read=is_read, is_read_receipt_requested=is_read_receipt_requested, parent_folder_id=parent_folder_id, received_date_time=received_date_time, reply_to=reply_to, sender=sender, sent_date_time=sent_date_time, subject=subject, to_recipients=to_recipients, unique_body=unique_body, web_link=web_link, attachments=attachments, extensions=extensions, multi_value_extended_properties=multi_value_extended_properties, single_value_extended_properties=single_value_extended_properties)
        content_type = kwargs.pop("content_type", "application/json")
        accept = "application/json"

        # Construct URL
        url = self.create_reply_all.metadata['url']  # type: ignore
        path_format_arguments = {
            'user-id': self._serialize.url("user_id", user_id, 'str'),
            'mailFolder-id': self._serialize.url("mail_folder_id", mail_folder_id, 'str'),
            'message-id': self._serialize.url("message_id", message_id, 'str'),
        }
        url = self._client.format_url(url, **path_format_arguments)

        # Construct parameters
        query_parameters = {}  # type: Dict[str, Any]

        # Construct headers
        header_parameters = {}  # type: Dict[str, Any]
        header_parameters['Content-Type'] = self._serialize.header("content_type", content_type, 'str')
        header_parameters['Accept'] = self._serialize.header("accept", accept, 'str')

        body_content_kwargs = {}  # type: Dict[str, Any]
        body_content = self._serialize.body(body, 'Paths3M6QbmUsersUserIdMailfoldersMailfolderIdMessagesMessageIdMicrosoftGraphCreatereplyallPostRequestbodyContentApplicationJsonSchema')
        body_content_kwargs['content'] = body_content
        request = self._client.post(url, query_parameters, header_parameters, **body_content_kwargs)
        pipeline_response = await self._client._pipeline.run(request, stream=False, **kwargs)
        response = pipeline_response.http_response

        if response.status_code not in [200]:
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            error = self._deserialize(models.OdataError, response)
            raise HttpResponseError(response=response, model=error, error_format=ARMErrorFormat)

        deserialized = self._deserialize('MicrosoftGraphMessage', pipeline_response)

        if cls:
            return cls(pipeline_response, deserialized, {})

        return deserialized
    create_reply_all.metadata = {'url': '/users/{user-id}/mailFolders/{mailFolder-id}/messages/{message-id}/microsoft.graph.createReplyAll'}  # type: ignore

    async def forward(
        self,
        user_id: str,
        mail_folder_id: str,
        message_id: str,
        to_recipients: Optional[List["models.MicrosoftGraphRecipient"]] = None,
        comment: Optional[str] = None,
        id: Optional[str] = None,
        categories: Optional[List[str]] = None,
        change_key: Optional[str] = None,
        created_date_time: Optional[datetime.datetime] = None,
        last_modified_date_time: Optional[datetime.datetime] = None,
        bcc_recipients: Optional[List["models.MicrosoftGraphRecipient"]] = None,
        body: Optional["models.MicrosoftGraphItemBody"] = None,
        body_preview: Optional[str] = None,
        cc_recipients: Optional[List["models.MicrosoftGraphRecipient"]] = None,
        conversation_id: Optional[str] = None,
        conversation_index: Optional[bytes] = None,
        flag: Optional["models.MicrosoftGraphFollowupFlag"] = None,
        from_parameter: Optional["models.MicrosoftGraphRecipient"] = None,
        has_attachments: Optional[bool] = None,
        importance: Optional[Union[str, "models.MicrosoftGraphImportance"]] = None,
        inference_classification: Optional[Union[str, "models.MicrosoftGraphInferenceClassificationType"]] = None,
        internet_message_headers: Optional[List["models.MicrosoftGraphInternetMessageHeader"]] = None,
        internet_message_id: Optional[str] = None,
        is_delivery_receipt_requested: Optional[bool] = None,
        is_draft: Optional[bool] = None,
        is_read: Optional[bool] = None,
        is_read_receipt_requested: Optional[bool] = None,
        parent_folder_id: Optional[str] = None,
        received_date_time: Optional[datetime.datetime] = None,
        reply_to: Optional[List["models.MicrosoftGraphRecipient"]] = None,
        sender: Optional["models.MicrosoftGraphRecipient"] = None,
        sent_date_time: Optional[datetime.datetime] = None,
        subject: Optional[str] = None,
        microsoft_graph_message_to_recipients: Optional[List["models.MicrosoftGraphRecipient"]] = None,
        unique_body: Optional["models.MicrosoftGraphItemBody"] = None,
        web_link: Optional[str] = None,
        attachments: Optional[List["models.MicrosoftGraphAttachment"]] = None,
        extensions: Optional[List["models.MicrosoftGraphExtension"]] = None,
        multi_value_extended_properties: Optional[List["models.MicrosoftGraphMultiValueLegacyExtendedProperty"]] = None,
        single_value_extended_properties: Optional[List["models.MicrosoftGraphSingleValueLegacyExtendedProperty"]] = None,
        **kwargs
    ) -> None:
        """Invoke action forward.

        Invoke action forward.

        :param user_id: key: id of user.
        :type user_id: str
        :param mail_folder_id: key: id of mailFolder.
        :type mail_folder_id: str
        :param message_id: key: id of message.
        :type message_id: str
        :param to_recipients:
        :type to_recipients: list[~users_actions.models.MicrosoftGraphRecipient]
        :param comment:
        :type comment: str
        :param id: Read-only.
        :type id: str
        :param categories: The categories associated with the item.
        :type categories: list[str]
        :param change_key: Identifies the version of the item. Every time the item is changed,
         changeKey changes as well. This allows Exchange to apply changes to the correct version of the
         object. Read-only.
        :type change_key: str
        :param created_date_time: The Timestamp type represents date and time information using ISO
         8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 would look like
         this: '2014-01-01T00:00:00Z'.
        :type created_date_time: ~datetime.datetime
        :param last_modified_date_time: The Timestamp type represents date and time information using
         ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 would look
         like this: '2014-01-01T00:00:00Z'.
        :type last_modified_date_time: ~datetime.datetime
        :param bcc_recipients: The Bcc: recipients for the message.
        :type bcc_recipients: list[~users_actions.models.MicrosoftGraphRecipient]
        :param body: itemBody.
        :type body: ~users_actions.models.MicrosoftGraphItemBody
        :param body_preview: The first 255 characters of the message body. It is in text format.
        :type body_preview: str
        :param cc_recipients: The Cc: recipients for the message.
        :type cc_recipients: list[~users_actions.models.MicrosoftGraphRecipient]
        :param conversation_id: The ID of the conversation the email belongs to.
        :type conversation_id: str
        :param conversation_index: Indicates the position of the message within the conversation.
        :type conversation_index: bytes
        :param flag: followupFlag.
        :type flag: ~users_actions.models.MicrosoftGraphFollowupFlag
        :param from_parameter: recipient.
        :type from_parameter: ~users_actions.models.MicrosoftGraphRecipient
        :param has_attachments: Indicates whether the message has attachments. This property doesn't
         include inline attachments, so if a message contains only inline attachments, this property is
         false. To verify the existence of inline attachments, parse the body property to look for a src
         attribute, such as :code:`<IMG src='cid:image001.jpg@01D26CD8.6C05F070'>`.
        :type has_attachments: bool
        :param importance:
        :type importance: str or ~users_actions.models.MicrosoftGraphImportance
        :param inference_classification:
        :type inference_classification: str or ~users_actions.models.MicrosoftGraphInferenceClassificationType
        :param internet_message_headers: A collection of message headers defined by RFC5322. The set
         includes message headers indicating the network path taken by a message from the sender to the
         recipient. It can also contain custom message headers that hold app data for the message.
         Returned only on applying a $select query option. Read-only.
        :type internet_message_headers: list[~users_actions.models.MicrosoftGraphInternetMessageHeader]
        :param internet_message_id: The message ID in the format specified by RFC2822.
        :type internet_message_id: str
        :param is_delivery_receipt_requested: Indicates whether a read receipt is requested for the
         message.
        :type is_delivery_receipt_requested: bool
        :param is_draft: Indicates whether the message is a draft. A message is a draft if it hasn't
         been sent yet.
        :type is_draft: bool
        :param is_read: Indicates whether the message has been read.
        :type is_read: bool
        :param is_read_receipt_requested: Indicates whether a read receipt is requested for the
         message.
        :type is_read_receipt_requested: bool
        :param parent_folder_id: The unique identifier for the message's parent mailFolder.
        :type parent_folder_id: str
        :param received_date_time: The date and time the message was received.
        :type received_date_time: ~datetime.datetime
        :param reply_to: The email addresses to use when replying.
        :type reply_to: list[~users_actions.models.MicrosoftGraphRecipient]
        :param sender: recipient.
        :type sender: ~users_actions.models.MicrosoftGraphRecipient
        :param sent_date_time: The date and time the message was sent.
        :type sent_date_time: ~datetime.datetime
        :param subject: The subject of the message.
        :type subject: str
        :param microsoft_graph_message_to_recipients: The To: recipients for the message.
        :type microsoft_graph_message_to_recipients: list[~users_actions.models.MicrosoftGraphRecipient]
        :param unique_body: itemBody.
        :type unique_body: ~users_actions.models.MicrosoftGraphItemBody
        :param web_link: The URL to open the message in Outlook Web App.You can append an ispopout
         argument to the end of the URL to change how the message is displayed. If ispopout is not
         present or if it is set to 1, then the message is shown in a popout window. If ispopout is set
         to 0, then the browser will show the message in the Outlook Web App review pane.The message
         will open in the browser if you are logged in to your mailbox via Outlook Web App. You will be
         prompted to login if you are not already logged in with the browser.This URL can be accessed
         from within an iFrame.
        :type web_link: str
        :param attachments: The fileAttachment and itemAttachment attachments for the message.
        :type attachments: list[~users_actions.models.MicrosoftGraphAttachment]
        :param extensions: The collection of open extensions defined for the message. Nullable.
        :type extensions: list[~users_actions.models.MicrosoftGraphExtension]
        :param multi_value_extended_properties: The collection of multi-value extended properties
         defined for the message. Nullable.
        :type multi_value_extended_properties: list[~users_actions.models.MicrosoftGraphMultiValueLegacyExtendedProperty]
        :param single_value_extended_properties: The collection of single-value extended properties
         defined for the message. Nullable.
        :type single_value_extended_properties: list[~users_actions.models.MicrosoftGraphSingleValueLegacyExtendedProperty]
        :keyword callable cls: A custom type or function that will be passed the direct response
        :return: None, or the result of cls(response)
        :rtype: None
        :raises: ~azure.core.exceptions.HttpResponseError
        """
        cls = kwargs.pop('cls', None)  # type: ClsType[None]
        error_map = {
            401: ClientAuthenticationError, 404: ResourceNotFoundError, 409: ResourceExistsError
        }
        error_map.update(kwargs.pop('error_map', {}))

        body = models.Paths1X7Dum0UsersUserIdMailfoldersMailfolderIdMessagesMessageIdMicrosoftGraphForwardPostRequestbodyContentApplicationJsonSchema(to_recipients=to_recipients, comment=comment, id=id, categories=categories, change_key=change_key, created_date_time=created_date_time, last_modified_date_time=last_modified_date_time, bcc_recipients=bcc_recipients, body=body, body_preview=body_preview, cc_recipients=cc_recipients, conversation_id=conversation_id, conversation_index=conversation_index, flag=flag, from_property=from_parameter, has_attachments=has_attachments, importance=importance, inference_classification=inference_classification, internet_message_headers=internet_message_headers, internet_message_id=internet_message_id, is_delivery_receipt_requested=is_delivery_receipt_requested, is_draft=is_draft, is_read=is_read, is_read_receipt_requested=is_read_receipt_requested, parent_folder_id=parent_folder_id, received_date_time=received_date_time, reply_to=reply_to, sender=sender, sent_date_time=sent_date_time, subject=subject, to_recipients_message_to_recipients=microsoft_graph_message_to_recipients, unique_body=unique_body, web_link=web_link, attachments=attachments, extensions=extensions, multi_value_extended_properties=multi_value_extended_properties, single_value_extended_properties=single_value_extended_properties)
        content_type = kwargs.pop("content_type", "application/json")
        accept = "application/json"

        # Construct URL
        url = self.forward.metadata['url']  # type: ignore
        path_format_arguments = {
            'user-id': self._serialize.url("user_id", user_id, 'str'),
            'mailFolder-id': self._serialize.url("mail_folder_id", mail_folder_id, 'str'),
            'message-id': self._serialize.url("message_id", message_id, 'str'),
        }
        url = self._client.format_url(url, **path_format_arguments)

        # Construct parameters
        query_parameters = {}  # type: Dict[str, Any]

        # Construct headers
        header_parameters = {}  # type: Dict[str, Any]
        header_parameters['Content-Type'] = self._serialize.header("content_type", content_type, 'str')
        header_parameters['Accept'] = self._serialize.header("accept", accept, 'str')

        body_content_kwargs = {}  # type: Dict[str, Any]
        body_content = self._serialize.body(body, 'Paths1X7Dum0UsersUserIdMailfoldersMailfolderIdMessagesMessageIdMicrosoftGraphForwardPostRequestbodyContentApplicationJsonSchema')
        body_content_kwargs['content'] = body_content
        request = self._client.post(url, query_parameters, header_parameters, **body_content_kwargs)
        pipeline_response = await self._client._pipeline.run(request, stream=False, **kwargs)
        response = pipeline_response.http_response

        if response.status_code not in [204]:
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            error = self._deserialize(models.OdataError, response)
            raise HttpResponseError(response=response, model=error, error_format=ARMErrorFormat)

        if cls:
            return cls(pipeline_response, None, {})

    forward.metadata = {'url': '/users/{user-id}/mailFolders/{mailFolder-id}/messages/{message-id}/microsoft.graph.forward'}  # type: ignore

    async def move(
        self,
        user_id: str,
        mail_folder_id: str,
        message_id: str,
        destination_id: Optional[str] = None,
        **kwargs
    ) -> "models.MicrosoftGraphMessage":
        """Invoke action move.

        Invoke action move.

        :param user_id: key: id of user.
        :type user_id: str
        :param mail_folder_id: key: id of mailFolder.
        :type mail_folder_id: str
        :param message_id: key: id of message.
        :type message_id: str
        :param destination_id:
        :type destination_id: str
        :keyword callable cls: A custom type or function that will be passed the direct response
        :return: MicrosoftGraphMessage, or the result of cls(response)
        :rtype: ~users_actions.models.MicrosoftGraphMessage
        :raises: ~azure.core.exceptions.HttpResponseError
        """
        cls = kwargs.pop('cls', None)  # type: ClsType["models.MicrosoftGraphMessage"]
        error_map = {
            401: ClientAuthenticationError, 404: ResourceNotFoundError, 409: ResourceExistsError
        }
        error_map.update(kwargs.pop('error_map', {}))

        body = models.Paths1Ph8596UsersUserIdMailfoldersMailfolderIdMessagesMessageIdMicrosoftGraphMovePostRequestbodyContentApplicationJsonSchema(destination_id=destination_id)
        content_type = kwargs.pop("content_type", "application/json")
        accept = "application/json"

        # Construct URL
        url = self.move.metadata['url']  # type: ignore
        path_format_arguments = {
            'user-id': self._serialize.url("user_id", user_id, 'str'),
            'mailFolder-id': self._serialize.url("mail_folder_id", mail_folder_id, 'str'),
            'message-id': self._serialize.url("message_id", message_id, 'str'),
        }
        url = self._client.format_url(url, **path_format_arguments)

        # Construct parameters
        query_parameters = {}  # type: Dict[str, Any]

        # Construct headers
        header_parameters = {}  # type: Dict[str, Any]
        header_parameters['Content-Type'] = self._serialize.header("content_type", content_type, 'str')
        header_parameters['Accept'] = self._serialize.header("accept", accept, 'str')

        body_content_kwargs = {}  # type: Dict[str, Any]
        body_content = self._serialize.body(body, 'Paths1Ph8596UsersUserIdMailfoldersMailfolderIdMessagesMessageIdMicrosoftGraphMovePostRequestbodyContentApplicationJsonSchema')
        body_content_kwargs['content'] = body_content
        request = self._client.post(url, query_parameters, header_parameters, **body_content_kwargs)
        pipeline_response = await self._client._pipeline.run(request, stream=False, **kwargs)
        response = pipeline_response.http_response

        if response.status_code not in [200]:
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            error = self._deserialize(models.OdataError, response)
            raise HttpResponseError(response=response, model=error, error_format=ARMErrorFormat)

        deserialized = self._deserialize('MicrosoftGraphMessage', pipeline_response)

        if cls:
            return cls(pipeline_response, deserialized, {})

        return deserialized
    move.metadata = {'url': '/users/{user-id}/mailFolders/{mailFolder-id}/messages/{message-id}/microsoft.graph.move'}  # type: ignore

    async def reply(
        self,
        user_id: str,
        mail_folder_id: str,
        message_id: str,
        comment: Optional[str] = None,
        id: Optional[str] = None,
        categories: Optional[List[str]] = None,
        change_key: Optional[str] = None,
        created_date_time: Optional[datetime.datetime] = None,
        last_modified_date_time: Optional[datetime.datetime] = None,
        bcc_recipients: Optional[List["models.MicrosoftGraphRecipient"]] = None,
        body: Optional["models.MicrosoftGraphItemBody"] = None,
        body_preview: Optional[str] = None,
        cc_recipients: Optional[List["models.MicrosoftGraphRecipient"]] = None,
        conversation_id: Optional[str] = None,
        conversation_index: Optional[bytes] = None,
        flag: Optional["models.MicrosoftGraphFollowupFlag"] = None,
        from_parameter: Optional["models.MicrosoftGraphRecipient"] = None,
        has_attachments: Optional[bool] = None,
        importance: Optional[Union[str, "models.MicrosoftGraphImportance"]] = None,
        inference_classification: Optional[Union[str, "models.MicrosoftGraphInferenceClassificationType"]] = None,
        internet_message_headers: Optional[List["models.MicrosoftGraphInternetMessageHeader"]] = None,
        internet_message_id: Optional[str] = None,
        is_delivery_receipt_requested: Optional[bool] = None,
        is_draft: Optional[bool] = None,
        is_read: Optional[bool] = None,
        is_read_receipt_requested: Optional[bool] = None,
        parent_folder_id: Optional[str] = None,
        received_date_time: Optional[datetime.datetime] = None,
        reply_to: Optional[List["models.MicrosoftGraphRecipient"]] = None,
        sender: Optional["models.MicrosoftGraphRecipient"] = None,
        sent_date_time: Optional[datetime.datetime] = None,
        subject: Optional[str] = None,
        to_recipients: Optional[List["models.MicrosoftGraphRecipient"]] = None,
        unique_body: Optional["models.MicrosoftGraphItemBody"] = None,
        web_link: Optional[str] = None,
        attachments: Optional[List["models.MicrosoftGraphAttachment"]] = None,
        extensions: Optional[List["models.MicrosoftGraphExtension"]] = None,
        multi_value_extended_properties: Optional[List["models.MicrosoftGraphMultiValueLegacyExtendedProperty"]] = None,
        single_value_extended_properties: Optional[List["models.MicrosoftGraphSingleValueLegacyExtendedProperty"]] = None,
        **kwargs
    ) -> None:
        """Invoke action reply.

        Invoke action reply.

        :param user_id: key: id of user.
        :type user_id: str
        :param mail_folder_id: key: id of mailFolder.
        :type mail_folder_id: str
        :param message_id: key: id of message.
        :type message_id: str
        :param comment:
        :type comment: str
        :param id: Read-only.
        :type id: str
        :param categories: The categories associated with the item.
        :type categories: list[str]
        :param change_key: Identifies the version of the item. Every time the item is changed,
         changeKey changes as well. This allows Exchange to apply changes to the correct version of the
         object. Read-only.
        :type change_key: str
        :param created_date_time: The Timestamp type represents date and time information using ISO
         8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 would look like
         this: '2014-01-01T00:00:00Z'.
        :type created_date_time: ~datetime.datetime
        :param last_modified_date_time: The Timestamp type represents date and time information using
         ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 would look
         like this: '2014-01-01T00:00:00Z'.
        :type last_modified_date_time: ~datetime.datetime
        :param bcc_recipients: The Bcc: recipients for the message.
        :type bcc_recipients: list[~users_actions.models.MicrosoftGraphRecipient]
        :param body: itemBody.
        :type body: ~users_actions.models.MicrosoftGraphItemBody
        :param body_preview: The first 255 characters of the message body. It is in text format.
        :type body_preview: str
        :param cc_recipients: The Cc: recipients for the message.
        :type cc_recipients: list[~users_actions.models.MicrosoftGraphRecipient]
        :param conversation_id: The ID of the conversation the email belongs to.
        :type conversation_id: str
        :param conversation_index: Indicates the position of the message within the conversation.
        :type conversation_index: bytes
        :param flag: followupFlag.
        :type flag: ~users_actions.models.MicrosoftGraphFollowupFlag
        :param from_parameter: recipient.
        :type from_parameter: ~users_actions.models.MicrosoftGraphRecipient
        :param has_attachments: Indicates whether the message has attachments. This property doesn't
         include inline attachments, so if a message contains only inline attachments, this property is
         false. To verify the existence of inline attachments, parse the body property to look for a src
         attribute, such as :code:`<IMG src='cid:image001.jpg@01D26CD8.6C05F070'>`.
        :type has_attachments: bool
        :param importance:
        :type importance: str or ~users_actions.models.MicrosoftGraphImportance
        :param inference_classification:
        :type inference_classification: str or ~users_actions.models.MicrosoftGraphInferenceClassificationType
        :param internet_message_headers: A collection of message headers defined by RFC5322. The set
         includes message headers indicating the network path taken by a message from the sender to the
         recipient. It can also contain custom message headers that hold app data for the message.
         Returned only on applying a $select query option. Read-only.
        :type internet_message_headers: list[~users_actions.models.MicrosoftGraphInternetMessageHeader]
        :param internet_message_id: The message ID in the format specified by RFC2822.
        :type internet_message_id: str
        :param is_delivery_receipt_requested: Indicates whether a read receipt is requested for the
         message.
        :type is_delivery_receipt_requested: bool
        :param is_draft: Indicates whether the message is a draft. A message is a draft if it hasn't
         been sent yet.
        :type is_draft: bool
        :param is_read: Indicates whether the message has been read.
        :type is_read: bool
        :param is_read_receipt_requested: Indicates whether a read receipt is requested for the
         message.
        :type is_read_receipt_requested: bool
        :param parent_folder_id: The unique identifier for the message's parent mailFolder.
        :type parent_folder_id: str
        :param received_date_time: The date and time the message was received.
        :type received_date_time: ~datetime.datetime
        :param reply_to: The email addresses to use when replying.
        :type reply_to: list[~users_actions.models.MicrosoftGraphRecipient]
        :param sender: recipient.
        :type sender: ~users_actions.models.MicrosoftGraphRecipient
        :param sent_date_time: The date and time the message was sent.
        :type sent_date_time: ~datetime.datetime
        :param subject: The subject of the message.
        :type subject: str
        :param to_recipients: The To: recipients for the message.
        :type to_recipients: list[~users_actions.models.MicrosoftGraphRecipient]
        :param unique_body: itemBody.
        :type unique_body: ~users_actions.models.MicrosoftGraphItemBody
        :param web_link: The URL to open the message in Outlook Web App.You can append an ispopout
         argument to the end of the URL to change how the message is displayed. If ispopout is not
         present or if it is set to 1, then the message is shown in a popout window. If ispopout is set
         to 0, then the browser will show the message in the Outlook Web App review pane.The message
         will open in the browser if you are logged in to your mailbox via Outlook Web App. You will be
         prompted to login if you are not already logged in with the browser.This URL can be accessed
         from within an iFrame.
        :type web_link: str
        :param attachments: The fileAttachment and itemAttachment attachments for the message.
        :type attachments: list[~users_actions.models.MicrosoftGraphAttachment]
        :param extensions: The collection of open extensions defined for the message. Nullable.
        :type extensions: list[~users_actions.models.MicrosoftGraphExtension]
        :param multi_value_extended_properties: The collection of multi-value extended properties
         defined for the message. Nullable.
        :type multi_value_extended_properties: list[~users_actions.models.MicrosoftGraphMultiValueLegacyExtendedProperty]
        :param single_value_extended_properties: The collection of single-value extended properties
         defined for the message. Nullable.
        :type single_value_extended_properties: list[~users_actions.models.MicrosoftGraphSingleValueLegacyExtendedProperty]
        :keyword callable cls: A custom type or function that will be passed the direct response
        :return: None, or the result of cls(response)
        :rtype: None
        :raises: ~azure.core.exceptions.HttpResponseError
        """
        cls = kwargs.pop('cls', None)  # type: ClsType[None]
        error_map = {
            401: ClientAuthenticationError, 404: ResourceNotFoundError, 409: ResourceExistsError
        }
        error_map.update(kwargs.pop('error_map', {}))

        body = models.Paths6Zjq1HUsersUserIdMailfoldersMailfolderIdMessagesMessageIdMicrosoftGraphReplyPostRequestbodyContentApplicationJsonSchema(comment=comment, id=id, categories=categories, change_key=change_key, created_date_time=created_date_time, last_modified_date_time=last_modified_date_time, bcc_recipients=bcc_recipients, body=body, body_preview=body_preview, cc_recipients=cc_recipients, conversation_id=conversation_id, conversation_index=conversation_index, flag=flag, from_property=from_parameter, has_attachments=has_attachments, importance=importance, inference_classification=inference_classification, internet_message_headers=internet_message_headers, internet_message_id=internet_message_id, is_delivery_receipt_requested=is_delivery_receipt_requested, is_draft=is_draft, is_read=is_read, is_read_receipt_requested=is_read_receipt_requested, parent_folder_id=parent_folder_id, received_date_time=received_date_time, reply_to=reply_to, sender=sender, sent_date_time=sent_date_time, subject=subject, to_recipients=to_recipients, unique_body=unique_body, web_link=web_link, attachments=attachments, extensions=extensions, multi_value_extended_properties=multi_value_extended_properties, single_value_extended_properties=single_value_extended_properties)
        content_type = kwargs.pop("content_type", "application/json")
        accept = "application/json"

        # Construct URL
        url = self.reply.metadata['url']  # type: ignore
        path_format_arguments = {
            'user-id': self._serialize.url("user_id", user_id, 'str'),
            'mailFolder-id': self._serialize.url("mail_folder_id", mail_folder_id, 'str'),
            'message-id': self._serialize.url("message_id", message_id, 'str'),
        }
        url = self._client.format_url(url, **path_format_arguments)

        # Construct parameters
        query_parameters = {}  # type: Dict[str, Any]

        # Construct headers
        header_parameters = {}  # type: Dict[str, Any]
        header_parameters['Content-Type'] = self._serialize.header("content_type", content_type, 'str')
        header_parameters['Accept'] = self._serialize.header("accept", accept, 'str')

        body_content_kwargs = {}  # type: Dict[str, Any]
        body_content = self._serialize.body(body, 'Paths6Zjq1HUsersUserIdMailfoldersMailfolderIdMessagesMessageIdMicrosoftGraphReplyPostRequestbodyContentApplicationJsonSchema')
        body_content_kwargs['content'] = body_content
        request = self._client.post(url, query_parameters, header_parameters, **body_content_kwargs)
        pipeline_response = await self._client._pipeline.run(request, stream=False, **kwargs)
        response = pipeline_response.http_response

        if response.status_code not in [204]:
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            error = self._deserialize(models.OdataError, response)
            raise HttpResponseError(response=response, model=error, error_format=ARMErrorFormat)

        if cls:
            return cls(pipeline_response, None, {})

    reply.metadata = {'url': '/users/{user-id}/mailFolders/{mailFolder-id}/messages/{message-id}/microsoft.graph.reply'}  # type: ignore

    async def reply_all(
        self,
        user_id: str,
        mail_folder_id: str,
        message_id: str,
        comment: Optional[str] = None,
        id: Optional[str] = None,
        categories: Optional[List[str]] = None,
        change_key: Optional[str] = None,
        created_date_time: Optional[datetime.datetime] = None,
        last_modified_date_time: Optional[datetime.datetime] = None,
        bcc_recipients: Optional[List["models.MicrosoftGraphRecipient"]] = None,
        body: Optional["models.MicrosoftGraphItemBody"] = None,
        body_preview: Optional[str] = None,
        cc_recipients: Optional[List["models.MicrosoftGraphRecipient"]] = None,
        conversation_id: Optional[str] = None,
        conversation_index: Optional[bytes] = None,
        flag: Optional["models.MicrosoftGraphFollowupFlag"] = None,
        from_parameter: Optional["models.MicrosoftGraphRecipient"] = None,
        has_attachments: Optional[bool] = None,
        importance: Optional[Union[str, "models.MicrosoftGraphImportance"]] = None,
        inference_classification: Optional[Union[str, "models.MicrosoftGraphInferenceClassificationType"]] = None,
        internet_message_headers: Optional[List["models.MicrosoftGraphInternetMessageHeader"]] = None,
        internet_message_id: Optional[str] = None,
        is_delivery_receipt_requested: Optional[bool] = None,
        is_draft: Optional[bool] = None,
        is_read: Optional[bool] = None,
        is_read_receipt_requested: Optional[bool] = None,
        parent_folder_id: Optional[str] = None,
        received_date_time: Optional[datetime.datetime] = None,
        reply_to: Optional[List["models.MicrosoftGraphRecipient"]] = None,
        sender: Optional["models.MicrosoftGraphRecipient"] = None,
        sent_date_time: Optional[datetime.datetime] = None,
        subject: Optional[str] = None,
        to_recipients: Optional[List["models.MicrosoftGraphRecipient"]] = None,
        unique_body: Optional["models.MicrosoftGraphItemBody"] = None,
        web_link: Optional[str] = None,
        attachments: Optional[List["models.MicrosoftGraphAttachment"]] = None,
        extensions: Optional[List["models.MicrosoftGraphExtension"]] = None,
        multi_value_extended_properties: Optional[List["models.MicrosoftGraphMultiValueLegacyExtendedProperty"]] = None,
        single_value_extended_properties: Optional[List["models.MicrosoftGraphSingleValueLegacyExtendedProperty"]] = None,
        **kwargs
    ) -> None:
        """Invoke action replyAll.

        Invoke action replyAll.

        :param user_id: key: id of user.
        :type user_id: str
        :param mail_folder_id: key: id of mailFolder.
        :type mail_folder_id: str
        :param message_id: key: id of message.
        :type message_id: str
        :param comment:
        :type comment: str
        :param id: Read-only.
        :type id: str
        :param categories: The categories associated with the item.
        :type categories: list[str]
        :param change_key: Identifies the version of the item. Every time the item is changed,
         changeKey changes as well. This allows Exchange to apply changes to the correct version of the
         object. Read-only.
        :type change_key: str
        :param created_date_time: The Timestamp type represents date and time information using ISO
         8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 would look like
         this: '2014-01-01T00:00:00Z'.
        :type created_date_time: ~datetime.datetime
        :param last_modified_date_time: The Timestamp type represents date and time information using
         ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 would look
         like this: '2014-01-01T00:00:00Z'.
        :type last_modified_date_time: ~datetime.datetime
        :param bcc_recipients: The Bcc: recipients for the message.
        :type bcc_recipients: list[~users_actions.models.MicrosoftGraphRecipient]
        :param body: itemBody.
        :type body: ~users_actions.models.MicrosoftGraphItemBody
        :param body_preview: The first 255 characters of the message body. It is in text format.
        :type body_preview: str
        :param cc_recipients: The Cc: recipients for the message.
        :type cc_recipients: list[~users_actions.models.MicrosoftGraphRecipient]
        :param conversation_id: The ID of the conversation the email belongs to.
        :type conversation_id: str
        :param conversation_index: Indicates the position of the message within the conversation.
        :type conversation_index: bytes
        :param flag: followupFlag.
        :type flag: ~users_actions.models.MicrosoftGraphFollowupFlag
        :param from_parameter: recipient.
        :type from_parameter: ~users_actions.models.MicrosoftGraphRecipient
        :param has_attachments: Indicates whether the message has attachments. This property doesn't
         include inline attachments, so if a message contains only inline attachments, this property is
         false. To verify the existence of inline attachments, parse the body property to look for a src
         attribute, such as :code:`<IMG src='cid:image001.jpg@01D26CD8.6C05F070'>`.
        :type has_attachments: bool
        :param importance:
        :type importance: str or ~users_actions.models.MicrosoftGraphImportance
        :param inference_classification:
        :type inference_classification: str or ~users_actions.models.MicrosoftGraphInferenceClassificationType
        :param internet_message_headers: A collection of message headers defined by RFC5322. The set
         includes message headers indicating the network path taken by a message from the sender to the
         recipient. It can also contain custom message headers that hold app data for the message.
         Returned only on applying a $select query option. Read-only.
        :type internet_message_headers: list[~users_actions.models.MicrosoftGraphInternetMessageHeader]
        :param internet_message_id: The message ID in the format specified by RFC2822.
        :type internet_message_id: str
        :param is_delivery_receipt_requested: Indicates whether a read receipt is requested for the
         message.
        :type is_delivery_receipt_requested: bool
        :param is_draft: Indicates whether the message is a draft. A message is a draft if it hasn't
         been sent yet.
        :type is_draft: bool
        :param is_read: Indicates whether the message has been read.
        :type is_read: bool
        :param is_read_receipt_requested: Indicates whether a read receipt is requested for the
         message.
        :type is_read_receipt_requested: bool
        :param parent_folder_id: The unique identifier for the message's parent mailFolder.
        :type parent_folder_id: str
        :param received_date_time: The date and time the message was received.
        :type received_date_time: ~datetime.datetime
        :param reply_to: The email addresses to use when replying.
        :type reply_to: list[~users_actions.models.MicrosoftGraphRecipient]
        :param sender: recipient.
        :type sender: ~users_actions.models.MicrosoftGraphRecipient
        :param sent_date_time: The date and time the message was sent.
        :type sent_date_time: ~datetime.datetime
        :param subject: The subject of the message.
        :type subject: str
        :param to_recipients: The To: recipients for the message.
        :type to_recipients: list[~users_actions.models.MicrosoftGraphRecipient]
        :param unique_body: itemBody.
        :type unique_body: ~users_actions.models.MicrosoftGraphItemBody
        :param web_link: The URL to open the message in Outlook Web App.You can append an ispopout
         argument to the end of the URL to change how the message is displayed. If ispopout is not
         present or if it is set to 1, then the message is shown in a popout window. If ispopout is set
         to 0, then the browser will show the message in the Outlook Web App review pane.The message
         will open in the browser if you are logged in to your mailbox via Outlook Web App. You will be
         prompted to login if you are not already logged in with the browser.This URL can be accessed
         from within an iFrame.
        :type web_link: str
        :param attachments: The fileAttachment and itemAttachment attachments for the message.
        :type attachments: list[~users_actions.models.MicrosoftGraphAttachment]
        :param extensions: The collection of open extensions defined for the message. Nullable.
        :type extensions: list[~users_actions.models.MicrosoftGraphExtension]
        :param multi_value_extended_properties: The collection of multi-value extended properties
         defined for the message. Nullable.
        :type multi_value_extended_properties: list[~users_actions.models.MicrosoftGraphMultiValueLegacyExtendedProperty]
        :param single_value_extended_properties: The collection of single-value extended properties
         defined for the message. Nullable.
        :type single_value_extended_properties: list[~users_actions.models.MicrosoftGraphSingleValueLegacyExtendedProperty]
        :keyword callable cls: A custom type or function that will be passed the direct response
        :return: None, or the result of cls(response)
        :rtype: None
        :raises: ~azure.core.exceptions.HttpResponseError
        """
        cls = kwargs.pop('cls', None)  # type: ClsType[None]
        error_map = {
            401: ClientAuthenticationError, 404: ResourceNotFoundError, 409: ResourceExistsError
        }
        error_map.update(kwargs.pop('error_map', {}))

        body = models.Paths16Mdb34UsersUserIdMailfoldersMailfolderIdMessagesMessageIdMicrosoftGraphReplyallPostRequestbodyContentApplicationJsonSchema(comment=comment, id=id, categories=categories, change_key=change_key, created_date_time=created_date_time, last_modified_date_time=last_modified_date_time, bcc_recipients=bcc_recipients, body=body, body_preview=body_preview, cc_recipients=cc_recipients, conversation_id=conversation_id, conversation_index=conversation_index, flag=flag, from_property=from_parameter, has_attachments=has_attachments, importance=importance, inference_classification=inference_classification, internet_message_headers=internet_message_headers, internet_message_id=internet_message_id, is_delivery_receipt_requested=is_delivery_receipt_requested, is_draft=is_draft, is_read=is_read, is_read_receipt_requested=is_read_receipt_requested, parent_folder_id=parent_folder_id, received_date_time=received_date_time, reply_to=reply_to, sender=sender, sent_date_time=sent_date_time, subject=subject, to_recipients=to_recipients, unique_body=unique_body, web_link=web_link, attachments=attachments, extensions=extensions, multi_value_extended_properties=multi_value_extended_properties, single_value_extended_properties=single_value_extended_properties)
        content_type = kwargs.pop("content_type", "application/json")
        accept = "application/json"

        # Construct URL
        url = self.reply_all.metadata['url']  # type: ignore
        path_format_arguments = {
            'user-id': self._serialize.url("user_id", user_id, 'str'),
            'mailFolder-id': self._serialize.url("mail_folder_id", mail_folder_id, 'str'),
            'message-id': self._serialize.url("message_id", message_id, 'str'),
        }
        url = self._client.format_url(url, **path_format_arguments)

        # Construct parameters
        query_parameters = {}  # type: Dict[str, Any]

        # Construct headers
        header_parameters = {}  # type: Dict[str, Any]
        header_parameters['Content-Type'] = self._serialize.header("content_type", content_type, 'str')
        header_parameters['Accept'] = self._serialize.header("accept", accept, 'str')

        body_content_kwargs = {}  # type: Dict[str, Any]
        body_content = self._serialize.body(body, 'Paths16Mdb34UsersUserIdMailfoldersMailfolderIdMessagesMessageIdMicrosoftGraphReplyallPostRequestbodyContentApplicationJsonSchema')
        body_content_kwargs['content'] = body_content
        request = self._client.post(url, query_parameters, header_parameters, **body_content_kwargs)
        pipeline_response = await self._client._pipeline.run(request, stream=False, **kwargs)
        response = pipeline_response.http_response

        if response.status_code not in [204]:
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            error = self._deserialize(models.OdataError, response)
            raise HttpResponseError(response=response, model=error, error_format=ARMErrorFormat)

        if cls:
            return cls(pipeline_response, None, {})

    reply_all.metadata = {'url': '/users/{user-id}/mailFolders/{mailFolder-id}/messages/{message-id}/microsoft.graph.replyAll'}  # type: ignore

    async def send(
        self,
        user_id: str,
        mail_folder_id: str,
        message_id: str,
        **kwargs
    ) -> None:
        """Invoke action send.

        Invoke action send.

        :param user_id: key: id of user.
        :type user_id: str
        :param mail_folder_id: key: id of mailFolder.
        :type mail_folder_id: str
        :param message_id: key: id of message.
        :type message_id: str
        :keyword callable cls: A custom type or function that will be passed the direct response
        :return: None, or the result of cls(response)
        :rtype: None
        :raises: ~azure.core.exceptions.HttpResponseError
        """
        cls = kwargs.pop('cls', None)  # type: ClsType[None]
        error_map = {
            401: ClientAuthenticationError, 404: ResourceNotFoundError, 409: ResourceExistsError
        }
        error_map.update(kwargs.pop('error_map', {}))
        accept = "application/json"

        # Construct URL
        url = self.send.metadata['url']  # type: ignore
        path_format_arguments = {
            'user-id': self._serialize.url("user_id", user_id, 'str'),
            'mailFolder-id': self._serialize.url("mail_folder_id", mail_folder_id, 'str'),
            'message-id': self._serialize.url("message_id", message_id, 'str'),
        }
        url = self._client.format_url(url, **path_format_arguments)

        # Construct parameters
        query_parameters = {}  # type: Dict[str, Any]

        # Construct headers
        header_parameters = {}  # type: Dict[str, Any]
        header_parameters['Accept'] = self._serialize.header("accept", accept, 'str')

        request = self._client.post(url, query_parameters, header_parameters)
        pipeline_response = await self._client._pipeline.run(request, stream=False, **kwargs)
        response = pipeline_response.http_response

        if response.status_code not in [204]:
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            error = self._deserialize(models.OdataError, response)
            raise HttpResponseError(response=response, model=error, error_format=ARMErrorFormat)

        if cls:
            return cls(pipeline_response, None, {})

    send.metadata = {'url': '/users/{user-id}/mailFolders/{mailFolder-id}/messages/{message-id}/microsoft.graph.send'}  # type: ignore
